// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuftest.proto

/*
Package protobuftest is a generated protocol buffer package.
It is generated from these files:
	protobuftest.proto
It has these top-level messages:
	Config
*/
package protobuftest

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Config struct {
	Currentversion string            `protobuf:"bytes,1,opt,name=currentversion" json:"currentversion,omitempty"`
	Upgrademsg     string            `protobuf:"bytes,2,opt,name=upgrademsg" json:"upgrademsg,omitempty"`
	Upgradeurl     string            `protobuf:"bytes,3,opt,name=upgradeurl" json:"upgradeurl,omitempty"`
	Datatypes      *Config_DataTypes `protobuf:"bytes,4,opt,name=datatypes" json:"datatypes,omitempty"`
}

func (m *Config) Reset()                    { *m = Config{} }
func (m *Config) String() string            { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()               {}
func (*Config) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Config) GetCurrentversion() string {
	if m != nil {
		return m.Currentversion
	}
	return ""
}

func (m *Config) GetUpgrademsg() string {
	if m != nil {
		return m.Upgrademsg
	}
	return ""
}

func (m *Config) GetUpgradeurl() string {
	if m != nil {
		return m.Upgradeurl
	}
	return ""
}

func (m *Config) GetDatatypes() *Config_DataTypes {
	if m != nil {
		return m.Datatypes
	}
	return nil
}

type Config_DataType struct {
	Invalidatedate string `protobuf:"bytes,1,opt,name=invalidatedate" json:"invalidatedate,omitempty"`
	Url            string `protobuf:"bytes,2,opt,name=url" json:"url,omitempty"`
	Cache          string `protobuf:"bytes,3,opt,name=cache" json:"cache,omitempty"`
	Autorefresh    string `protobuf:"bytes,4,opt,name=autorefresh" json:"autorefresh,omitempty"`
}

func (m *Config_DataType) Reset()                    { *m = Config_DataType{} }
func (m *Config_DataType) String() string            { return proto.CompactTextString(m) }
func (*Config_DataType) ProtoMessage()               {}
func (*Config_DataType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *Config_DataType) GetInvalidatedate() string {
	if m != nil {
		return m.Invalidatedate
	}
	return ""
}

func (m *Config_DataType) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Config_DataType) GetCache() string {
	if m != nil {
		return m.Cache
	}
	return ""
}

func (m *Config_DataType) GetAutorefresh() string {
	if m != nil {
		return m.Autorefresh
	}
	return ""
}

type Config_DataTypes struct {
	Package        *Config_DataType `protobuf:"bytes,1,opt,name=package" json:"package,omitempty"`
	Request        *Config_DataType `protobuf:"bytes,2,opt,name=request" json:"request,omitempty"`
	Milestones     *Config_DataType `protobuf:"bytes,3,opt,name=milestones" json:"milestones,omitempty"`
	Milestonerange *Config_DataType `protobuf:"bytes,4,opt,name=milestonerange" json:"milestonerange,omitempty"`
}

func (m *Config_DataTypes) Reset()                    { *m = Config_DataTypes{} }
func (m *Config_DataTypes) String() string            { return proto.CompactTextString(m) }
func (*Config_DataTypes) ProtoMessage()               {}
func (*Config_DataTypes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 1} }

func (m *Config_DataTypes) GetPackage() *Config_DataType {
	if m != nil {
		return m.Package
	}
	return nil
}

func (m *Config_DataTypes) GetRequest() *Config_DataType {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *Config_DataTypes) GetMilestones() *Config_DataType {
	if m != nil {
		return m.Milestones
	}
	return nil
}

func (m *Config_DataTypes) GetMilestonerange() *Config_DataType {
	if m != nil {
		return m.Milestonerange
	}
	return nil
}

func init() {
	proto.RegisterType((*Config)(nil), "Config")
	proto.RegisterType((*Config_DataType)(nil), "Config.DataType")
	proto.RegisterType((*Config_DataTypes)(nil), "Config.DataTypes")
}

func init() { proto.RegisterFile("protobuftest.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 287 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xc1, 0x4a, 0xf3, 0x40,
	0x10, 0xc7, 0xc9, 0xd7, 0xcf, 0x6a, 0xa6, 0x50, 0xea, 0xe2, 0x21, 0xf4, 0x20, 0xc1, 0x83, 0x14,
	0x0f, 0x51, 0xea, 0xc5, 0xbb, 0x3e, 0x41, 0xf0, 0x05, 0xa6, 0xc9, 0x24, 0x0d, 0xa6, 0xbb, 0x71,
	0x77, 0xb6, 0x20, 0xf8, 0x8e, 0x3e, 0x8b, 0x6f, 0x20, 0xbb, 0x49, 0x6a, 0x1a, 0x7b, 0x08, 0x64,
	0xfe, 0xff, 0xdf, 0x32, 0x3f, 0x76, 0x41, 0x34, 0x5a, 0xb1, 0xda, 0xd8, 0x82, 0xc9, 0x70, 0xe2,
	0x87, 0x9b, 0xef, 0x09, 0x4c, 0x9f, 0x95, 0x2c, 0xaa, 0x52, 0xdc, 0xc2, 0x3c, 0xb3, 0x5a, 0x93,
	0xe4, 0x3d, 0x69, 0x53, 0x29, 0x19, 0x05, 0x71, 0xb0, 0x0a, 0xd3, 0x51, 0x2a, 0xae, 0x01, 0x6c,
	0x53, 0x6a, 0xcc, 0x69, 0x67, 0xca, 0xe8, 0x9f, 0x67, 0x06, 0xc9, 0xa0, 0xb7, 0xba, 0x8e, 0x26,
	0x47, 0xbd, 0xd5, 0xb5, 0xb8, 0x87, 0x30, 0x47, 0x46, 0xfe, 0x68, 0xc8, 0x44, 0xff, 0xe3, 0x60,
	0x35, 0x5b, 0x5f, 0x26, 0xad, 0x43, 0xf2, 0x82, 0x8c, 0xaf, 0xae, 0x48, 0x7f, 0x99, 0xe5, 0x27,
	0x5c, 0xf4, 0xb9, 0x93, 0xac, 0xe4, 0x1e, 0xeb, 0x2a, 0x47, 0x26, 0xf7, 0xf5, 0x92, 0xc7, 0xa9,
	0x58, 0xc0, 0xc4, 0x6d, 0x6f, 0xed, 0xdc, 0xaf, 0xb8, 0x82, 0xb3, 0x0c, 0xb3, 0x2d, 0x75, 0x46,
	0xed, 0x20, 0x62, 0x98, 0xa1, 0x65, 0xa5, 0xa9, 0xd0, 0x64, 0xb6, 0x5e, 0x27, 0x4c, 0x87, 0xd1,
	0xf2, 0x2b, 0x80, 0xf0, 0xa0, 0x25, 0xee, 0xe0, 0xbc, 0xc1, 0xec, 0x0d, 0xcb, 0x76, 0xf1, 0x6c,
	0xbd, 0x18, 0xab, 0xa7, 0x3d, 0xe0, 0x58, 0x4d, 0xef, 0x96, 0x0c, 0x7b, 0x8f, 0x93, 0x6c, 0x07,
	0x88, 0x07, 0x80, 0x5d, 0x55, 0x93, 0x61, 0x25, 0xc9, 0x78, 0xc5, 0x53, 0xf8, 0x80, 0x11, 0x4f,
	0x30, 0x3f, 0x4c, 0x1a, 0x65, 0x49, 0xdd, 0x5d, 0xfe, 0x3d, 0x35, 0xe2, 0x36, 0x53, 0xff, 0xf4,
	0x8f, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xd3, 0x84, 0xcf, 0xb1, 0x10, 0x02, 0x00, 0x00,
}
