// Code generated by protoc-gen-go. DO NOT EDIT.
// source: icebox.proto

/*
Package protos is a generated protocol buffer package.

It is generated from these files:
	icebox.proto

It has these top-level messages:
	Timestamp
	IceboxMessage
	Error
	Header
	ReplyHeader
	HiRequest
	HiReply
	NegotiateRequest
	NegotiateReply
	StartRequest
	StartReply
	ConversationRequest
	ConversationReply
	EndRequest
	EndReply
	CheckRequest
	CheckReply
	InitRequest
	InitReply
	PingRequest
	PingReply
	AddCoinRequest
	AddCoinReply
	CreateAddressRequest
	CreateAddressReply
	CreateSecretRequest
	CreateSecretReply
	AddSecretRequest
	AddSecretReply
	SignTxRequest
	SignTxReply
	SignMsgRequest
	SignMsgReply
	ListCoinRequest
	ListCoinReply
	GetAddressRequest
	GetAddressReply
	ListAddressRequest
	Address
	ListAddressReply
	ListSecretRequest
	Secret
	ListSecretReply
	RemoveCoinRequest
	RemoveCoinReply
	DeleteSecretRequest
	DeleteSecretReply
	DeleteAddressRequest
	DeleteAddressReply
	ResetRequest
	ResetReply
*/
package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
//import _ "."

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type IceboxMessage_Type int32

const (
	IceboxMessage_UNDEFINED      IceboxMessage_Type = 0
	IceboxMessage_ERROR          IceboxMessage_Type = 1
	IceboxMessage_HELLO          IceboxMessage_Type = 2
	IceboxMessage_NEGOTIATE      IceboxMessage_Type = 3
	IceboxMessage_START          IceboxMessage_Type = 4
	IceboxMessage_END            IceboxMessage_Type = 5
	IceboxMessage_CHECK          IceboxMessage_Type = 6
	IceboxMessage_INIT           IceboxMessage_Type = 7
	IceboxMessage_PING           IceboxMessage_Type = 8
	IceboxMessage_RESET          IceboxMessage_Type = 9
	IceboxMessage_ADD_COIN       IceboxMessage_Type = 10
	IceboxMessage_CREATE_ADDRESS IceboxMessage_Type = 11
	IceboxMessage_CREATE_SECRET  IceboxMessage_Type = 12
	IceboxMessage_LIST_COIN      IceboxMessage_Type = 13
	IceboxMessage_LIST_ADDRESS   IceboxMessage_Type = 14
	IceboxMessage_LIST_SECRET    IceboxMessage_Type = 15
	IceboxMessage_SIGN_TX        IceboxMessage_Type = 16
	IceboxMessage_REMOVE_COIN    IceboxMessage_Type = 17
	IceboxMessage_DELETE_ADDRESS IceboxMessage_Type = 18
	IceboxMessage_DELETE_SECRET  IceboxMessage_Type = 19
	IceboxMessage_GET_ADDRESS    IceboxMessage_Type = 20
	IceboxMessage_GET_SECRET     IceboxMessage_Type = 21
	IceboxMessage_SIGN_MSG       IceboxMessage_Type = 22
)

var IceboxMessage_Type_name = map[int32]string{
	0:  "UNDEFINED",
	1:  "ERROR",
	2:  "HELLO",
	3:  "NEGOTIATE",
	4:  "START",
	5:  "END",
	6:  "CHECK",
	7:  "INIT",
	8:  "PING",
	9:  "RESET",
	10: "ADD_COIN",
	11: "CREATE_ADDRESS",
	12: "CREATE_SECRET",
	13: "LIST_COIN",
	14: "LIST_ADDRESS",
	15: "LIST_SECRET",
	16: "SIGN_TX",
	17: "REMOVE_COIN",
	18: "DELETE_ADDRESS",
	19: "DELETE_SECRET",
	20: "GET_ADDRESS",
	21: "GET_SECRET",
	22: "SIGN_MSG",
}
var IceboxMessage_Type_value = map[string]int32{
	"UNDEFINED":      0,
	"ERROR":          1,
	"HELLO":          2,
	"NEGOTIATE":      3,
	"START":          4,
	"END":            5,
	"CHECK":          6,
	"INIT":           7,
	"PING":           8,
	"RESET":          9,
	"ADD_COIN":       10,
	"CREATE_ADDRESS": 11,
	"CREATE_SECRET":  12,
	"LIST_COIN":      13,
	"LIST_ADDRESS":   14,
	"LIST_SECRET":    15,
	"SIGN_TX":        16,
	"REMOVE_COIN":    17,
	"DELETE_ADDRESS": 18,
	"DELETE_SECRET":  19,
	"GET_ADDRESS":    20,
	"GET_SECRET":     21,
	"SIGN_MSG":       22,
}

func (x IceboxMessage_Type) Enum() *IceboxMessage_Type {
	p := new(IceboxMessage_Type)
	*p = x
	return p
}
func (x IceboxMessage_Type) String() string {
	return proto.EnumName(IceboxMessage_Type_name, int32(x))
}
func (x *IceboxMessage_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(IceboxMessage_Type_value, data, "IceboxMessage_Type")
	if err != nil {
		return err
	}
	*x = IceboxMessage_Type(value)
	return nil
}
func (IceboxMessage_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type Timestamp struct {
	// Represents seconds of UTC time since Unix epoch
	// 1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to
	// 9999-12-31T23:59:59Z inclusive.
	Seconds *int64 `protobuf:"varint,1,req,name=seconds" json:"seconds,omitempty"`
	// Non-negative fractions of a second at nanosecond resolution. Negative
	// second values with fractions must still have non-negative nanos values
	// that count forward in time. Must be from 0 to 999,999,999
	// inclusive.
	Nanos            *int32 `protobuf:"varint,2,req,name=nanos" json:"nanos,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Timestamp) Reset()                    { *m = Timestamp{} }
func (m *Timestamp) String() string            { return proto.CompactTextString(m) }
func (*Timestamp) ProtoMessage()               {}
func (*Timestamp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Timestamp) GetSeconds() int64 {
	if m != nil && m.Seconds != nil {
		return *m.Seconds
	}
	return 0
}

func (m *Timestamp) GetNanos() int32 {
	if m != nil && m.Nanos != nil {
		return *m.Nanos
	}
	return 0
}

type IceboxMessage struct {
	//    required uint32 version = 1[default = 1];  // 消息版本号
	//    required Type type = 2;
	//    required uint32 session_id = 3;
	Header           *IceboxMessage_Header `protobuf:"bytes,1,req,name=header" json:"header,omitempty"`
	Payload          []byte                `protobuf:"bytes,2,req,name=payload" json:"payload,omitempty"`
	Signature        []byte                `protobuf:"bytes,3,req,name=signature" json:"signature,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *IceboxMessage) Reset()                    { *m = IceboxMessage{} }
func (m *IceboxMessage) String() string            { return proto.CompactTextString(m) }
func (*IceboxMessage) ProtoMessage()               {}
func (*IceboxMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *IceboxMessage) GetHeader() *IceboxMessage_Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *IceboxMessage) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *IceboxMessage) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type IceboxMessage_Header struct {
	Version          *uint32             `protobuf:"varint,1,req,name=version,def=1" json:"version,omitempty"`
	Type             *IceboxMessage_Type `protobuf:"varint,2,req,name=type,enum=IceboxMessage_Type" json:"type,omitempty"`
	Timestamp        *Timestamp          `protobuf:"bytes,3,req,name=timestamp" json:"timestamp,omitempty"`
	SessionId        *uint32             `protobuf:"varint,4,req,name=session_id,json=sessionId" json:"session_id,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *IceboxMessage_Header) Reset()                    { *m = IceboxMessage_Header{} }
func (m *IceboxMessage_Header) String() string            { return proto.CompactTextString(m) }
func (*IceboxMessage_Header) ProtoMessage()               {}
func (*IceboxMessage_Header) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

const Default_IceboxMessage_Header_Version uint32 = 1

func (m *IceboxMessage_Header) GetVersion() uint32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return Default_IceboxMessage_Header_Version
}

func (m *IceboxMessage_Header) GetType() IceboxMessage_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return IceboxMessage_UNDEFINED
}

func (m *IceboxMessage_Header) GetTimestamp() *Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *IceboxMessage_Header) GetSessionId() uint32 {
	if m != nil && m.SessionId != nil {
		return *m.SessionId
	}
	return 0
}

type Error struct {
	Code             *int32  `protobuf:"varint,1,req,name=code" json:"code,omitempty"`
	Message          *string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (m *Error) String() string            { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Error) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

type Header struct {
	Ver              *uint32 `protobuf:"varint,1,req,name=ver,def=1" json:"ver,omitempty"`
	Sn               *uint32 `protobuf:"varint,2,req,name=sn" json:"sn,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Header) Reset()                    { *m = Header{} }
func (m *Header) String() string            { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()               {}
func (*Header) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

const Default_Header_Ver uint32 = 1

func (m *Header) GetVer() uint32 {
	if m != nil && m.Ver != nil {
		return *m.Ver
	}
	return Default_Header_Ver
}

func (m *Header) GetSn() uint32 {
	if m != nil && m.Sn != nil {
		return *m.Sn
	}
	return 0
}

type ReplyHeader struct {
	Ver              *uint32 `protobuf:"varint,1,req,name=ver,def=1" json:"ver,omitempty"`
	Sn               *uint32 `protobuf:"varint,2,req,name=sn" json:"sn,omitempty"`
	Code             *uint32 `protobuf:"varint,3,req,name=code" json:"code,omitempty"`
	Message          *string `protobuf:"bytes,4,opt,name=message" json:"message,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ReplyHeader) Reset()                    { *m = ReplyHeader{} }
func (m *ReplyHeader) String() string            { return proto.CompactTextString(m) }
func (*ReplyHeader) ProtoMessage()               {}
func (*ReplyHeader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

const Default_ReplyHeader_Ver uint32 = 1

func (m *ReplyHeader) GetVer() uint32 {
	if m != nil && m.Ver != nil {
		return *m.Ver
	}
	return Default_ReplyHeader_Ver
}

func (m *ReplyHeader) GetSn() uint32 {
	if m != nil && m.Sn != nil {
		return *m.Sn
	}
	return 0
}

func (m *ReplyHeader) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *ReplyHeader) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

type HiRequest struct {
	//    required Header header = 1;
	MagicA           *int64 `protobuf:"varint,2,req,name=magicA" json:"magicA,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *HiRequest) Reset()                    { *m = HiRequest{} }
func (m *HiRequest) String() string            { return proto.CompactTextString(m) }
func (*HiRequest) ProtoMessage()               {}
func (*HiRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *HiRequest) GetMagicA() int64 {
	if m != nil && m.MagicA != nil {
		return *m.MagicA
	}
	return 0
}

type HiReply struct {
	//    required ReplyHeader header = 1;
	MagicB           *int64 `protobuf:"varint,2,req,name=magicB" json:"magicB,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *HiReply) Reset()                    { *m = HiReply{} }
func (m *HiReply) String() string            { return proto.CompactTextString(m) }
func (*HiReply) ProtoMessage()               {}
func (*HiReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *HiReply) GetMagicB() int64 {
	if m != nil && m.MagicB != nil {
		return *m.MagicB
	}
	return 0
}

type NegotiateRequest struct {
	KeyA             *string `protobuf:"bytes,2,req,name=keyA" json:"keyA,omitempty"`
	Hash             *string `protobuf:"bytes,3,req,name=hash" json:"hash,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *NegotiateRequest) Reset()                    { *m = NegotiateRequest{} }
func (m *NegotiateRequest) String() string            { return proto.CompactTextString(m) }
func (*NegotiateRequest) ProtoMessage()               {}
func (*NegotiateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *NegotiateRequest) GetKeyA() string {
	if m != nil && m.KeyA != nil {
		return *m.KeyA
	}
	return ""
}

func (m *NegotiateRequest) GetHash() string {
	if m != nil && m.Hash != nil {
		return *m.Hash
	}
	return ""
}

type NegotiateReply struct {
	KeyB             *string `protobuf:"bytes,2,req,name=keyB" json:"keyB,omitempty"`
	Hash             *string `protobuf:"bytes,3,req,name=hash" json:"hash,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *NegotiateReply) Reset()                    { *m = NegotiateReply{} }
func (m *NegotiateReply) String() string            { return proto.CompactTextString(m) }
func (*NegotiateReply) ProtoMessage()               {}
func (*NegotiateReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *NegotiateReply) GetKeyB() string {
	if m != nil && m.KeyB != nil {
		return *m.KeyB
	}
	return ""
}

func (m *NegotiateReply) GetHash() string {
	if m != nil && m.Hash != nil {
		return *m.Hash
	}
	return ""
}

type StartRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *StartRequest) Reset()                    { *m = StartRequest{} }
func (m *StartRequest) String() string            { return proto.CompactTextString(m) }
func (*StartRequest) ProtoMessage()               {}
func (*StartRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type StartReply struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *StartReply) Reset()                    { *m = StartReply{} }
func (m *StartReply) String() string            { return proto.CompactTextString(m) }
func (*StartReply) ProtoMessage()               {}
func (*StartReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type ConversationRequest struct {
	//    required Header header = 1;
	// session id
	SessionId *uint32 `protobuf:"varint,2,req,name=session_id,json=sessionId" json:"session_id,omitempty"`
	// message id
	MessageId *uint32 `protobuf:"varint,3,req,name=message_id,json=messageId" json:"message_id,omitempty"`
	// encrypted message
	Content *string `protobuf:"bytes,4,req,name=content" json:"content,omitempty"`
	// signatures
	Signature        *string `protobuf:"bytes,5,req,name=signature" json:"signature,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ConversationRequest) Reset()                    { *m = ConversationRequest{} }
func (m *ConversationRequest) String() string            { return proto.CompactTextString(m) }
func (*ConversationRequest) ProtoMessage()               {}
func (*ConversationRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *ConversationRequest) GetSessionId() uint32 {
	if m != nil && m.SessionId != nil {
		return *m.SessionId
	}
	return 0
}

func (m *ConversationRequest) GetMessageId() uint32 {
	if m != nil && m.MessageId != nil {
		return *m.MessageId
	}
	return 0
}

func (m *ConversationRequest) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

func (m *ConversationRequest) GetSignature() string {
	if m != nil && m.Signature != nil {
		return *m.Signature
	}
	return ""
}

type ConversationReply struct {
	//    required ReplyHeader header = 1;
	// session id
	SessionId *uint32 `protobuf:"varint,2,req,name=session_id,json=sessionId" json:"session_id,omitempty"`
	// message id
	MessageId *uint32 `protobuf:"varint,3,req,name=message_id,json=messageId" json:"message_id,omitempty"`
	// encrypted message
	Content *string `protobuf:"bytes,4,req,name=content" json:"content,omitempty"`
	// signatures
	Signature        *string `protobuf:"bytes,5,req,name=signature" json:"signature,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ConversationReply) Reset()                    { *m = ConversationReply{} }
func (m *ConversationReply) String() string            { return proto.CompactTextString(m) }
func (*ConversationReply) ProtoMessage()               {}
func (*ConversationReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *ConversationReply) GetSessionId() uint32 {
	if m != nil && m.SessionId != nil {
		return *m.SessionId
	}
	return 0
}

func (m *ConversationReply) GetMessageId() uint32 {
	if m != nil && m.MessageId != nil {
		return *m.MessageId
	}
	return 0
}

func (m *ConversationReply) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

func (m *ConversationReply) GetSignature() string {
	if m != nil && m.Signature != nil {
		return *m.Signature
	}
	return ""
}

type EndRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *EndRequest) Reset()                    { *m = EndRequest{} }
func (m *EndRequest) String() string            { return proto.CompactTextString(m) }
func (*EndRequest) ProtoMessage()               {}
func (*EndRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

type EndReply struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *EndReply) Reset()                    { *m = EndReply{} }
func (m *EndReply) String() string            { return proto.CompactTextString(m) }
func (*EndReply) ProtoMessage()               {}
func (*EndReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

type CheckRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CheckRequest) Reset()                    { *m = CheckRequest{} }
func (m *CheckRequest) String() string            { return proto.CompactTextString(m) }
func (*CheckRequest) ProtoMessage()               {}
func (*CheckRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

type CheckReply struct {
	//    required ReplyHeader header = 1;
	State *int32 `protobuf:"varint,2,req,name=state" json:"state,omitempty"`
	// if paired then return dev_id=hash(id+app_id)
	DevId            *string `protobuf:"bytes,3,opt,name=dev_id,json=devId" json:"dev_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CheckReply) Reset()                    { *m = CheckReply{} }
func (m *CheckReply) String() string            { return proto.CompactTextString(m) }
func (*CheckReply) ProtoMessage()               {}
func (*CheckReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *CheckReply) GetState() int32 {
	if m != nil && m.State != nil {
		return *m.State
	}
	return 0
}

func (m *CheckReply) GetDevId() string {
	if m != nil && m.DevId != nil {
		return *m.DevId
	}
	return ""
}

type InitRequest struct {
	//    required Header header = 1;
	// 真实设备是没有这个字段的
	Password         *string `protobuf:"bytes,2,req,name=password" json:"password,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *InitRequest) Reset()                    { *m = InitRequest{} }
func (m *InitRequest) String() string            { return proto.CompactTextString(m) }
func (*InitRequest) ProtoMessage()               {}
func (*InitRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *InitRequest) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

type InitReply struct {
	//    required ReplyHeader header = 1;
	DevId            *string `protobuf:"bytes,2,req,name=dev_id,json=devId" json:"dev_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *InitReply) Reset()                    { *m = InitReply{} }
func (m *InitReply) String() string            { return proto.CompactTextString(m) }
func (*InitReply) ProtoMessage()               {}
func (*InitReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *InitReply) GetDevId() string {
	if m != nil && m.DevId != nil {
		return *m.DevId
	}
	return ""
}

// The request message containing the user's name.
type PingRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *PingRequest) Reset()                    { *m = PingRequest{} }
func (m *PingRequest) String() string            { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()               {}
func (*PingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

// The response message containing the greetings
type PingReply struct {
	//    required ReplyHeader header = 1;
	Timestamp        *int64 `protobuf:"varint,2,req,name=timestamp" json:"timestamp,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PingReply) Reset()                    { *m = PingReply{} }
func (m *PingReply) String() string            { return proto.CompactTextString(m) }
func (*PingReply) ProtoMessage()               {}
func (*PingReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *PingReply) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

// if coin_type have exists in cointable, then failed
type AddCoinRequest struct {
	Type             *uint32 `protobuf:"varint,2,req,name=type" json:"type,omitempty"`
	Idx              *uint32 `protobuf:"varint,3,req,name=idx" json:"idx,omitempty"`
	Symbol           *string `protobuf:"bytes,4,req,name=symbol" json:"symbol,omitempty"`
	Name             *string `protobuf:"bytes,5,req,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AddCoinRequest) Reset()                    { *m = AddCoinRequest{} }
func (m *AddCoinRequest) String() string            { return proto.CompactTextString(m) }
func (*AddCoinRequest) ProtoMessage()               {}
func (*AddCoinRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *AddCoinRequest) GetType() uint32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *AddCoinRequest) GetIdx() uint32 {
	if m != nil && m.Idx != nil {
		return *m.Idx
	}
	return 0
}

func (m *AddCoinRequest) GetSymbol() string {
	if m != nil && m.Symbol != nil {
		return *m.Symbol
	}
	return ""
}

func (m *AddCoinRequest) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type AddCoinReply struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *AddCoinReply) Reset()                    { *m = AddCoinReply{} }
func (m *AddCoinReply) String() string            { return proto.CompactTextString(m) }
func (*AddCoinReply) ProtoMessage()               {}
func (*AddCoinReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

type CreateAddressRequest struct {
	Password         *string `protobuf:"bytes,1,req,name=password" json:"password,omitempty"`
	Type             *uint32 `protobuf:"varint,2,req,name=type" json:"type,omitempty"`
	Idx              *uint32 `protobuf:"varint,3,opt,name=idx" json:"idx,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CreateAddressRequest) Reset()                    { *m = CreateAddressRequest{} }
func (m *CreateAddressRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateAddressRequest) ProtoMessage()               {}
func (*CreateAddressRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *CreateAddressRequest) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

func (m *CreateAddressRequest) GetType() uint32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *CreateAddressRequest) GetIdx() uint32 {
	if m != nil && m.Idx != nil {
		return *m.Idx
	}
	return 0
}

type CreateAddressReply struct {
	Type             *uint32 `protobuf:"varint,1,req,name=type" json:"type,omitempty"`
	Idx              *uint32 `protobuf:"varint,2,req,name=idx" json:"idx,omitempty"`
	Address          *string `protobuf:"bytes,3,req,name=address" json:"address,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CreateAddressReply) Reset()                    { *m = CreateAddressReply{} }
func (m *CreateAddressReply) String() string            { return proto.CompactTextString(m) }
func (*CreateAddressReply) ProtoMessage()               {}
func (*CreateAddressReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *CreateAddressReply) GetType() uint32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *CreateAddressReply) GetIdx() uint32 {
	if m != nil && m.Idx != nil {
		return *m.Idx
	}
	return 0
}

func (m *CreateAddressReply) GetAddress() string {
	if m != nil && m.Address != nil {
		return *m.Address
	}
	return ""
}

type CreateSecretRequest struct {
	Password         *string `protobuf:"bytes,1,req,name=password" json:"password,omitempty"`
	Type             *uint32 `protobuf:"varint,2,req,name=type" json:"type,omitempty"`
	Site             *uint32 `protobuf:"varint,3,req,name=site" json:"site,omitempty"`
	Account          *uint32 `protobuf:"varint,4,req,name=account" json:"account,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CreateSecretRequest) Reset()                    { *m = CreateSecretRequest{} }
func (m *CreateSecretRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateSecretRequest) ProtoMessage()               {}
func (*CreateSecretRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *CreateSecretRequest) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

func (m *CreateSecretRequest) GetType() uint32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *CreateSecretRequest) GetSite() uint32 {
	if m != nil && m.Site != nil {
		return *m.Site
	}
	return 0
}

func (m *CreateSecretRequest) GetAccount() uint32 {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return 0
}

type CreateSecretReply struct {
	Type             *uint32 `protobuf:"varint,1,req,name=type" json:"type,omitempty"`
	Site             *uint32 `protobuf:"varint,2,req,name=site" json:"site,omitempty"`
	Account          *uint32 `protobuf:"varint,3,req,name=account" json:"account,omitempty"`
	Index            *uint32 `protobuf:"varint,4,req,name=index" json:"index,omitempty"`
	Secret           *string `protobuf:"bytes,5,req,name=secret" json:"secret,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CreateSecretReply) Reset()                    { *m = CreateSecretReply{} }
func (m *CreateSecretReply) String() string            { return proto.CompactTextString(m) }
func (*CreateSecretReply) ProtoMessage()               {}
func (*CreateSecretReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *CreateSecretReply) GetType() uint32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *CreateSecretReply) GetSite() uint32 {
	if m != nil && m.Site != nil {
		return *m.Site
	}
	return 0
}

func (m *CreateSecretReply) GetAccount() uint32 {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return 0
}

func (m *CreateSecretReply) GetIndex() uint32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func (m *CreateSecretReply) GetSecret() string {
	if m != nil && m.Secret != nil {
		return *m.Secret
	}
	return ""
}

// 保存用户自己的秘密
type AddSecretRequest struct {
	Password         *string `protobuf:"bytes,1,req,name=password" json:"password,omitempty"`
	Type             *uint32 `protobuf:"varint,2,req,name=type" json:"type,omitempty"`
	Site             *uint32 `protobuf:"varint,3,req,name=site" json:"site,omitempty"`
	Account          *uint32 `protobuf:"varint,4,req,name=account" json:"account,omitempty"`
	Secret           *string `protobuf:"bytes,5,req,name=secret" json:"secret,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AddSecretRequest) Reset()                    { *m = AddSecretRequest{} }
func (m *AddSecretRequest) String() string            { return proto.CompactTextString(m) }
func (*AddSecretRequest) ProtoMessage()               {}
func (*AddSecretRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *AddSecretRequest) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

func (m *AddSecretRequest) GetType() uint32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *AddSecretRequest) GetSite() uint32 {
	if m != nil && m.Site != nil {
		return *m.Site
	}
	return 0
}

func (m *AddSecretRequest) GetAccount() uint32 {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return 0
}

func (m *AddSecretRequest) GetSecret() string {
	if m != nil && m.Secret != nil {
		return *m.Secret
	}
	return ""
}

type AddSecretReply struct {
	Type             *uint32 `protobuf:"varint,1,req,name=type" json:"type,omitempty"`
	Site             *uint32 `protobuf:"varint,2,req,name=site" json:"site,omitempty"`
	Account          *uint32 `protobuf:"varint,3,req,name=account" json:"account,omitempty"`
	Idx              *uint32 `protobuf:"varint,4,req,name=idx" json:"idx,omitempty"`
	Secret           *string `protobuf:"bytes,5,req,name=secret" json:"secret,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AddSecretReply) Reset()                    { *m = AddSecretReply{} }
func (m *AddSecretReply) String() string            { return proto.CompactTextString(m) }
func (*AddSecretReply) ProtoMessage()               {}
func (*AddSecretReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *AddSecretReply) GetType() uint32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *AddSecretReply) GetSite() uint32 {
	if m != nil && m.Site != nil {
		return *m.Site
	}
	return 0
}

func (m *AddSecretReply) GetAccount() uint32 {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return 0
}

func (m *AddSecretReply) GetIdx() uint32 {
	if m != nil && m.Idx != nil {
		return *m.Idx
	}
	return 0
}

func (m *AddSecretReply) GetSecret() string {
	if m != nil && m.Secret != nil {
		return *m.Secret
	}
	return ""
}

type SignTxRequest struct {
	Password *string `protobuf:"bytes,1,req,name=password" json:"password,omitempty"`
	Type     *uint32 `protobuf:"varint,2,req,name=type" json:"type,omitempty"`
	Idx      *uint32 `protobuf:"varint,3,req,name=idx" json:"idx,omitempty"`
	Amount   *uint64 `protobuf:"varint,4,req,name=amount" json:"amount,omitempty"`
	// TODO: 该最大值未经验证
	Dest *string `protobuf:"bytes,5,req,name=dest" json:"dest,omitempty"`
	// TODO: 该最大值未经验证
	TxHash           *string `protobuf:"bytes,6,req,name=tx_hash,json=txHash" json:"tx_hash,omitempty"`
	TxIdx            *uint32 `protobuf:"varint,7,req,name=tx_idx,json=txIdx" json:"tx_idx,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SignTxRequest) Reset()                    { *m = SignTxRequest{} }
func (m *SignTxRequest) String() string            { return proto.CompactTextString(m) }
func (*SignTxRequest) ProtoMessage()               {}
func (*SignTxRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *SignTxRequest) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

func (m *SignTxRequest) GetType() uint32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *SignTxRequest) GetIdx() uint32 {
	if m != nil && m.Idx != nil {
		return *m.Idx
	}
	return 0
}

func (m *SignTxRequest) GetAmount() uint64 {
	if m != nil && m.Amount != nil {
		return *m.Amount
	}
	return 0
}

func (m *SignTxRequest) GetDest() string {
	if m != nil && m.Dest != nil {
		return *m.Dest
	}
	return ""
}

func (m *SignTxRequest) GetTxHash() string {
	if m != nil && m.TxHash != nil {
		return *m.TxHash
	}
	return ""
}

func (m *SignTxRequest) GetTxIdx() uint32 {
	if m != nil && m.TxIdx != nil {
		return *m.TxIdx
	}
	return 0
}

type SignTxReply struct {
	// TODO: 该最大值未经验证
	SignedTx         []byte `protobuf:"bytes,2,req,name=signedTx" json:"signedTx,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SignTxReply) Reset()                    { *m = SignTxReply{} }
func (m *SignTxReply) String() string            { return proto.CompactTextString(m) }
func (*SignTxReply) ProtoMessage()               {}
func (*SignTxReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

func (m *SignTxReply) GetSignedTx() []byte {
	if m != nil {
		return m.SignedTx
	}
	return nil
}

type SignMsgRequest struct {
	Password         *string `protobuf:"bytes,1,req,name=password" json:"password,omitempty"`
	Type             *uint32 `protobuf:"varint,2,req,name=type" json:"type,omitempty"`
	Idx              *uint32 `protobuf:"varint,3,req,name=idx" json:"idx,omitempty"`
	Message          []byte  `protobuf:"bytes,4,req,name=message" json:"message,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SignMsgRequest) Reset()                    { *m = SignMsgRequest{} }
func (m *SignMsgRequest) String() string            { return proto.CompactTextString(m) }
func (*SignMsgRequest) ProtoMessage()               {}
func (*SignMsgRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

func (m *SignMsgRequest) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

func (m *SignMsgRequest) GetType() uint32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *SignMsgRequest) GetIdx() uint32 {
	if m != nil && m.Idx != nil {
		return *m.Idx
	}
	return 0
}

func (m *SignMsgRequest) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

type SignMsgReply struct {
	Signed           []byte `protobuf:"bytes,1,req,name=signed" json:"signed,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SignMsgReply) Reset()                    { *m = SignMsgReply{} }
func (m *SignMsgReply) String() string            { return proto.CompactTextString(m) }
func (*SignMsgReply) ProtoMessage()               {}
func (*SignMsgReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{32} }

func (m *SignMsgReply) GetSigned() []byte {
	if m != nil {
		return m.Signed
	}
	return nil
}

// list all of wallets
type ListCoinRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *ListCoinRequest) Reset()                    { *m = ListCoinRequest{} }
func (m *ListCoinRequest) String() string            { return proto.CompactTextString(m) }
func (*ListCoinRequest) ProtoMessage()               {}
func (*ListCoinRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{33} }

type ListCoinReply struct {
	Max              *uint32  `protobuf:"varint,2,req,name=max" json:"max,omitempty"`
	Type             []uint32 `protobuf:"varint,3,rep,name=type" json:"type,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ListCoinReply) Reset()                    { *m = ListCoinReply{} }
func (m *ListCoinReply) String() string            { return proto.CompactTextString(m) }
func (*ListCoinReply) ProtoMessage()               {}
func (*ListCoinReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{34} }

func (m *ListCoinReply) GetMax() uint32 {
	if m != nil && m.Max != nil {
		return *m.Max
	}
	return 0
}

func (m *ListCoinReply) GetType() []uint32 {
	if m != nil {
		return m.Type
	}
	return nil
}

// 查询单条记录
type GetAddressRequest struct {
	Password         *string `protobuf:"bytes,1,req,name=password" json:"password,omitempty"`
	Type             *uint32 `protobuf:"varint,2,req,name=type" json:"type,omitempty"`
	Idx              *uint32 `protobuf:"varint,3,req,name=idx" json:"idx,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetAddressRequest) Reset()                    { *m = GetAddressRequest{} }
func (m *GetAddressRequest) String() string            { return proto.CompactTextString(m) }
func (*GetAddressRequest) ProtoMessage()               {}
func (*GetAddressRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{35} }

func (m *GetAddressRequest) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

func (m *GetAddressRequest) GetType() uint32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *GetAddressRequest) GetIdx() uint32 {
	if m != nil && m.Idx != nil {
		return *m.Idx
	}
	return 0
}

type GetAddressReply struct {
	Addr             *Address `protobuf:"bytes,1,req,name=addr" json:"addr,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *GetAddressReply) Reset()                    { *m = GetAddressReply{} }
func (m *GetAddressReply) String() string            { return proto.CompactTextString(m) }
func (*GetAddressReply) ProtoMessage()               {}
func (*GetAddressReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{36} }

func (m *GetAddressReply) GetAddr() *Address {
	if m != nil {
		return m.Addr
	}
	return nil
}

type ListAddressRequest struct {
	Password         *string `protobuf:"bytes,1,req,name=password" json:"password,omitempty"`
	Type             *uint32 `protobuf:"varint,2,req,name=type" json:"type,omitempty"`
	Offset           *uint32 `protobuf:"varint,3,req,name=offset" json:"offset,omitempty"`
	Limit            *uint32 `protobuf:"varint,4,req,name=limit" json:"limit,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ListAddressRequest) Reset()                    { *m = ListAddressRequest{} }
func (m *ListAddressRequest) String() string            { return proto.CompactTextString(m) }
func (*ListAddressRequest) ProtoMessage()               {}
func (*ListAddressRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{37} }

func (m *ListAddressRequest) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

func (m *ListAddressRequest) GetType() uint32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *ListAddressRequest) GetOffset() uint32 {
	if m != nil && m.Offset != nil {
		return *m.Offset
	}
	return 0
}

func (m *ListAddressRequest) GetLimit() uint32 {
	if m != nil && m.Limit != nil {
		return *m.Limit
	}
	return 0
}

type Address struct {
	Type             *uint32 `protobuf:"varint,1,req,name=type" json:"type,omitempty"`
	Idx              *uint32 `protobuf:"varint,2,req,name=idx" json:"idx,omitempty"`
	Name             *string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	SAddr            *string `protobuf:"bytes,4,req,name=s_addr,json=sAddr" json:"s_addr,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Address) Reset()                    { *m = Address{} }
func (m *Address) String() string            { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()               {}
func (*Address) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{38} }

func (m *Address) GetType() uint32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *Address) GetIdx() uint32 {
	if m != nil && m.Idx != nil {
		return *m.Idx
	}
	return 0
}

func (m *Address) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Address) GetSAddr() string {
	if m != nil && m.SAddr != nil {
		return *m.SAddr
	}
	return ""
}

type ListAddressReply struct {
	TotalRecords     *uint32    `protobuf:"varint,1,req,name=total_records,json=totalRecords" json:"total_records,omitempty"`
	TotalPages       *uint32    `protobuf:"varint,2,req,name=total_pages,json=totalPages" json:"total_pages,omitempty"`
	Limit            *uint32    `protobuf:"varint,3,req,name=limit" json:"limit,omitempty"`
	Offset           *uint32    `protobuf:"varint,4,req,name=offset" json:"offset,omitempty"`
	Addr             []*Address `protobuf:"bytes,5,rep,name=addr" json:"addr,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *ListAddressReply) Reset()                    { *m = ListAddressReply{} }
func (m *ListAddressReply) String() string            { return proto.CompactTextString(m) }
func (*ListAddressReply) ProtoMessage()               {}
func (*ListAddressReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{39} }

func (m *ListAddressReply) GetTotalRecords() uint32 {
	if m != nil && m.TotalRecords != nil {
		return *m.TotalRecords
	}
	return 0
}

func (m *ListAddressReply) GetTotalPages() uint32 {
	if m != nil && m.TotalPages != nil {
		return *m.TotalPages
	}
	return 0
}

func (m *ListAddressReply) GetLimit() uint32 {
	if m != nil && m.Limit != nil {
		return *m.Limit
	}
	return 0
}

func (m *ListAddressReply) GetOffset() uint32 {
	if m != nil && m.Offset != nil {
		return *m.Offset
	}
	return 0
}

func (m *ListAddressReply) GetAddr() []*Address {
	if m != nil {
		return m.Addr
	}
	return nil
}

type ListSecretRequest struct {
	Password         *string `protobuf:"bytes,1,req,name=password" json:"password,omitempty"`
	Type             *uint32 `protobuf:"varint,2,req,name=type" json:"type,omitempty"`
	Site             *uint32 `protobuf:"varint,3,opt,name=site" json:"site,omitempty"`
	Account          *uint32 `protobuf:"varint,4,opt,name=account" json:"account,omitempty"`
	Offset           *uint32 `protobuf:"varint,5,req,name=offset" json:"offset,omitempty"`
	Limit            *uint32 `protobuf:"varint,6,req,name=limit" json:"limit,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ListSecretRequest) Reset()                    { *m = ListSecretRequest{} }
func (m *ListSecretRequest) String() string            { return proto.CompactTextString(m) }
func (*ListSecretRequest) ProtoMessage()               {}
func (*ListSecretRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{40} }

func (m *ListSecretRequest) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

func (m *ListSecretRequest) GetType() uint32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *ListSecretRequest) GetSite() uint32 {
	if m != nil && m.Site != nil {
		return *m.Site
	}
	return 0
}

func (m *ListSecretRequest) GetAccount() uint32 {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return 0
}

func (m *ListSecretRequest) GetOffset() uint32 {
	if m != nil && m.Offset != nil {
		return *m.Offset
	}
	return 0
}

func (m *ListSecretRequest) GetLimit() uint32 {
	if m != nil && m.Limit != nil {
		return *m.Limit
	}
	return 0
}

type Secret struct {
	Type             *uint32 `protobuf:"varint,1,req,name=type" json:"type,omitempty"`
	Site             *uint32 `protobuf:"varint,2,req,name=site" json:"site,omitempty"`
	Account          *uint32 `protobuf:"varint,3,req,name=account" json:"account,omitempty"`
	Idx              *uint32 `protobuf:"varint,4,req,name=idx" json:"idx,omitempty"`
	SSecret          *string `protobuf:"bytes,5,req,name=s_secret,json=sSecret" json:"s_secret,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Secret) Reset()                    { *m = Secret{} }
func (m *Secret) String() string            { return proto.CompactTextString(m) }
func (*Secret) ProtoMessage()               {}
func (*Secret) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{41} }

func (m *Secret) GetType() uint32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *Secret) GetSite() uint32 {
	if m != nil && m.Site != nil {
		return *m.Site
	}
	return 0
}

func (m *Secret) GetAccount() uint32 {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return 0
}

func (m *Secret) GetIdx() uint32 {
	if m != nil && m.Idx != nil {
		return *m.Idx
	}
	return 0
}

func (m *Secret) GetSSecret() string {
	if m != nil && m.SSecret != nil {
		return *m.SSecret
	}
	return ""
}

type ListSecretReply struct {
	TotalRecords     *uint32   `protobuf:"varint,1,req,name=total_records,json=totalRecords" json:"total_records,omitempty"`
	TotalPages       *uint32   `protobuf:"varint,2,req,name=total_pages,json=totalPages" json:"total_pages,omitempty"`
	Limit            *uint32   `protobuf:"varint,3,req,name=limit" json:"limit,omitempty"`
	Offset           *uint32   `protobuf:"varint,4,req,name=offset" json:"offset,omitempty"`
	Secret           []*Secret `protobuf:"bytes,5,rep,name=secret" json:"secret,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *ListSecretReply) Reset()                    { *m = ListSecretReply{} }
func (m *ListSecretReply) String() string            { return proto.CompactTextString(m) }
func (*ListSecretReply) ProtoMessage()               {}
func (*ListSecretReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{42} }

func (m *ListSecretReply) GetTotalRecords() uint32 {
	if m != nil && m.TotalRecords != nil {
		return *m.TotalRecords
	}
	return 0
}

func (m *ListSecretReply) GetTotalPages() uint32 {
	if m != nil && m.TotalPages != nil {
		return *m.TotalPages
	}
	return 0
}

func (m *ListSecretReply) GetLimit() uint32 {
	if m != nil && m.Limit != nil {
		return *m.Limit
	}
	return 0
}

func (m *ListSecretReply) GetOffset() uint32 {
	if m != nil && m.Offset != nil {
		return *m.Offset
	}
	return 0
}

func (m *ListSecretReply) GetSecret() []*Secret {
	if m != nil {
		return m.Secret
	}
	return nil
}

type RemoveCoinRequest struct {
	Password         *string `protobuf:"bytes,1,req,name=password" json:"password,omitempty"`
	Type             *uint32 `protobuf:"varint,2,req,name=type" json:"type,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RemoveCoinRequest) Reset()                    { *m = RemoveCoinRequest{} }
func (m *RemoveCoinRequest) String() string            { return proto.CompactTextString(m) }
func (*RemoveCoinRequest) ProtoMessage()               {}
func (*RemoveCoinRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{43} }

func (m *RemoveCoinRequest) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

func (m *RemoveCoinRequest) GetType() uint32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

type RemoveCoinReply struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RemoveCoinReply) Reset()                    { *m = RemoveCoinReply{} }
func (m *RemoveCoinReply) String() string            { return proto.CompactTextString(m) }
func (*RemoveCoinReply) ProtoMessage()               {}
func (*RemoveCoinReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{44} }

type DeleteSecretRequest struct {
	Password         *string `protobuf:"bytes,1,req,name=password" json:"password,omitempty"`
	Type             *uint32 `protobuf:"varint,2,req,name=type" json:"type,omitempty"`
	Idx              *uint32 `protobuf:"varint,3,req,name=idx" json:"idx,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DeleteSecretRequest) Reset()                    { *m = DeleteSecretRequest{} }
func (m *DeleteSecretRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteSecretRequest) ProtoMessage()               {}
func (*DeleteSecretRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{45} }

func (m *DeleteSecretRequest) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

func (m *DeleteSecretRequest) GetType() uint32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *DeleteSecretRequest) GetIdx() uint32 {
	if m != nil && m.Idx != nil {
		return *m.Idx
	}
	return 0
}

type DeleteSecretReply struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *DeleteSecretReply) Reset()                    { *m = DeleteSecretReply{} }
func (m *DeleteSecretReply) String() string            { return proto.CompactTextString(m) }
func (*DeleteSecretReply) ProtoMessage()               {}
func (*DeleteSecretReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{46} }

type DeleteAddressRequest struct {
	Password         *string `protobuf:"bytes,1,req,name=password" json:"password,omitempty"`
	Type             *uint32 `protobuf:"varint,2,req,name=type" json:"type,omitempty"`
	Idx              *uint32 `protobuf:"varint,3,req,name=idx" json:"idx,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DeleteAddressRequest) Reset()                    { *m = DeleteAddressRequest{} }
func (m *DeleteAddressRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteAddressRequest) ProtoMessage()               {}
func (*DeleteAddressRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{47} }

func (m *DeleteAddressRequest) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

func (m *DeleteAddressRequest) GetType() uint32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *DeleteAddressRequest) GetIdx() uint32 {
	if m != nil && m.Idx != nil {
		return *m.Idx
	}
	return 0
}

type DeleteAddressReply struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *DeleteAddressReply) Reset()                    { *m = DeleteAddressReply{} }
func (m *DeleteAddressReply) String() string            { return proto.CompactTextString(m) }
func (*DeleteAddressReply) ProtoMessage()               {}
func (*DeleteAddressReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{48} }

type ResetRequest struct {
	Password         *string `protobuf:"bytes,1,req,name=password" json:"password,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ResetRequest) Reset()                    { *m = ResetRequest{} }
func (m *ResetRequest) String() string            { return proto.CompactTextString(m) }
func (*ResetRequest) ProtoMessage()               {}
func (*ResetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{49} }

func (m *ResetRequest) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

type ResetReply struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *ResetReply) Reset()                    { *m = ResetReply{} }
func (m *ResetReply) String() string            { return proto.CompactTextString(m) }
func (*ResetReply) ProtoMessage()               {}
func (*ResetReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{50} }

func init() {
	proto.RegisterType((*Timestamp)(nil), "Timestamp")
	proto.RegisterType((*IceboxMessage)(nil), "IceboxMessage")
	proto.RegisterType((*IceboxMessage_Header)(nil), "IceboxMessage.Header")
	proto.RegisterType((*Error)(nil), "Error")
	proto.RegisterType((*Header)(nil), "Header")
	proto.RegisterType((*ReplyHeader)(nil), "ReplyHeader")
	proto.RegisterType((*HiRequest)(nil), "HiRequest")
	proto.RegisterType((*HiReply)(nil), "HiReply")
	proto.RegisterType((*NegotiateRequest)(nil), "NegotiateRequest")
	proto.RegisterType((*NegotiateReply)(nil), "NegotiateReply")
	proto.RegisterType((*StartRequest)(nil), "StartRequest")
	proto.RegisterType((*StartReply)(nil), "StartReply")
	proto.RegisterType((*ConversationRequest)(nil), "ConversationRequest")
	proto.RegisterType((*ConversationReply)(nil), "ConversationReply")
	proto.RegisterType((*EndRequest)(nil), "EndRequest")
	proto.RegisterType((*EndReply)(nil), "EndReply")
	proto.RegisterType((*CheckRequest)(nil), "CheckRequest")
	proto.RegisterType((*CheckReply)(nil), "CheckReply")
	proto.RegisterType((*InitRequest)(nil), "InitRequest")
	proto.RegisterType((*InitReply)(nil), "InitReply")
	proto.RegisterType((*PingRequest)(nil), "PingRequest")
	proto.RegisterType((*PingReply)(nil), "PingReply")
	proto.RegisterType((*AddCoinRequest)(nil), "AddCoinRequest")
	proto.RegisterType((*AddCoinReply)(nil), "AddCoinReply")
	proto.RegisterType((*CreateAddressRequest)(nil), "CreateAddressRequest")
	proto.RegisterType((*CreateAddressReply)(nil), "CreateAddressReply")
	proto.RegisterType((*CreateSecretRequest)(nil), "CreateSecretRequest")
	proto.RegisterType((*CreateSecretReply)(nil), "CreateSecretReply")
	proto.RegisterType((*AddSecretRequest)(nil), "AddSecretRequest")
	proto.RegisterType((*AddSecretReply)(nil), "AddSecretReply")
	proto.RegisterType((*SignTxRequest)(nil), "SignTxRequest")
	proto.RegisterType((*SignTxReply)(nil), "SignTxReply")
	proto.RegisterType((*SignMsgRequest)(nil), "SignMsgRequest")
	proto.RegisterType((*SignMsgReply)(nil), "SignMsgReply")
	proto.RegisterType((*ListCoinRequest)(nil), "ListCoinRequest")
	proto.RegisterType((*ListCoinReply)(nil), "ListCoinReply")
	proto.RegisterType((*GetAddressRequest)(nil), "GetAddressRequest")
	proto.RegisterType((*GetAddressReply)(nil), "GetAddressReply")
	proto.RegisterType((*ListAddressRequest)(nil), "ListAddressRequest")
	proto.RegisterType((*Address)(nil), "Address")
	proto.RegisterType((*ListAddressReply)(nil), "ListAddressReply")
	proto.RegisterType((*ListSecretRequest)(nil), "ListSecretRequest")
	proto.RegisterType((*Secret)(nil), "Secret")
	proto.RegisterType((*ListSecretReply)(nil), "ListSecretReply")
	proto.RegisterType((*RemoveCoinRequest)(nil), "RemoveCoinRequest")
	proto.RegisterType((*RemoveCoinReply)(nil), "RemoveCoinReply")
	proto.RegisterType((*DeleteSecretRequest)(nil), "DeleteSecretRequest")
	proto.RegisterType((*DeleteSecretReply)(nil), "DeleteSecretReply")
	proto.RegisterType((*DeleteAddressRequest)(nil), "DeleteAddressRequest")
	proto.RegisterType((*DeleteAddressReply)(nil), "DeleteAddressReply")
	proto.RegisterType((*ResetRequest)(nil), "ResetRequest")
	proto.RegisterType((*ResetReply)(nil), "ResetReply")
	proto.RegisterEnum("IceboxMessage_Type", IceboxMessage_Type_name, IceboxMessage_Type_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Icebox service

type IceboxClient interface {
	// 会话需要加密
	Chat(ctx context.Context, in *IceboxMessage, opts ...grpc.CallOption) (*IceboxMessage, error)
}

type iceboxClient struct {
	cc *grpc.ClientConn
}

func NewIceboxClient(cc *grpc.ClientConn) IceboxClient {
	return &iceboxClient{cc}
}

func (c *iceboxClient) Chat(ctx context.Context, in *IceboxMessage, opts ...grpc.CallOption) (*IceboxMessage, error) {
	out := new(IceboxMessage)
	err := grpc.Invoke(ctx, "/Icebox/Chat", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Icebox service

type IceboxServer interface {
	// 会话需要加密
	Chat(context.Context, *IceboxMessage) (*IceboxMessage, error)
}

func RegisterIceboxServer(s *grpc.Server, srv IceboxServer) {
	s.RegisterService(&_Icebox_serviceDesc, srv)
}

func _Icebox_Chat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IceboxMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IceboxServer).Chat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Icebox/Chat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IceboxServer).Chat(ctx, req.(*IceboxMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Icebox_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Icebox",
	HandlerType: (*IceboxServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Chat",
			Handler:    _Icebox_Chat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "icebox.proto",
}

func init() { proto.RegisterFile("icebox.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1523 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x58, 0xdd, 0x6e, 0x1b, 0xd5,
	0x16, 0xee, 0xd8, 0xe3, 0x9f, 0x59, 0xfe, 0xc9, 0x78, 0x27, 0xad, 0xd2, 0x9c, 0xfe, 0xb8, 0x53,
	0xe9, 0x9c, 0xf4, 0x48, 0xcd, 0x51, 0x73, 0x75, 0x28, 0xa0, 0xe2, 0xd8, 0x43, 0x62, 0x91, 0x38,
	0xd5, 0xb6, 0x0b, 0x15, 0x5c, 0x58, 0x13, 0xcf, 0xae, 0x33, 0xaa, 0x3d, 0x63, 0xbc, 0xa7, 0xc1,
	0xe6, 0x02, 0x21, 0x71, 0x05, 0xdc, 0xf5, 0x02, 0x2e, 0x79, 0x00, 0xc4, 0x13, 0xf0, 0x18, 0xbc,
	0x03, 0xcf, 0x81, 0xd6, 0xfe, 0xf1, 0x8c, 0xdd, 0x40, 0x5b, 0xa5, 0xd0, 0xbb, 0xbd, 0xd6, 0xde,
	0x6b, 0xad, 0x6f, 0xfd, 0xec, 0x6f, 0xb6, 0x0d, 0xe5, 0x60, 0xc0, 0x4e, 0xa2, 0xd9, 0xce, 0x64,
	0x1a, 0xc5, 0xd1, 0x56, 0x39, 0xf4, 0xc2, 0x68, 0x72, 0x22, 0x25, 0xe7, 0x5d, 0xb0, 0x7a, 0xc1,
	0x98, 0xf1, 0xd8, 0x1b, 0x4f, 0xc8, 0x26, 0x14, 0x38, 0x1b, 0x44, 0xa1, 0xcf, 0x37, 0x8d, 0x7a,
	0x66, 0x3b, 0x4b, 0xb5, 0x48, 0x36, 0x20, 0x87, 0x66, 0x7c, 0x33, 0x53, 0xcf, 0x6c, 0xe7, 0xa8,
	0x14, 0x9c, 0xdf, 0x4d, 0xa8, 0xb4, 0x85, 0xef, 0x23, 0xc6, 0xb9, 0x37, 0x64, 0xe4, 0x2e, 0xe4,
	0x4f, 0x99, 0xe7, 0xb3, 0xa9, 0x70, 0x50, 0xda, 0xbd, 0xbc, 0xb3, 0xb4, 0xbf, 0x73, 0x20, 0x36,
	0xa9, 0x3a, 0x84, 0x01, 0x27, 0xde, 0x7c, 0x14, 0x79, 0xbe, 0x70, 0x5c, 0xa6, 0x5a, 0x24, 0xd7,
	0xc0, 0xe2, 0xc1, 0x30, 0xf4, 0xe2, 0x67, 0x53, 0xb6, 0x99, 0x15, 0x7b, 0x89, 0x62, 0xeb, 0x47,
	0x03, 0xf2, 0xd2, 0x15, 0xf9, 0x17, 0x14, 0xce, 0xd8, 0x94, 0x07, 0x51, 0x28, 0x42, 0x56, 0xee,
	0x1b, 0xf7, 0xa8, 0xd6, 0x90, 0xff, 0x80, 0x19, 0xcf, 0x27, 0x4c, 0x38, 0xaf, 0xee, 0xae, 0xaf,
	0x80, 0xe9, 0xcd, 0x27, 0x8c, 0x8a, 0x03, 0x64, 0x1b, 0xac, 0x58, 0x97, 0x41, 0x84, 0x2b, 0xed,
	0xc2, 0xce, 0xa2, 0x30, 0x34, 0xd9, 0x24, 0xd7, 0x01, 0x38, 0xe3, 0xe8, 0xbd, 0x1f, 0xf8, 0x9b,
	0x26, 0x86, 0xa4, 0x96, 0xd2, 0xb4, 0x7d, 0xe7, 0xb7, 0x0c, 0x98, 0xe8, 0x97, 0x54, 0xc0, 0x7a,
	0xd4, 0x69, 0xb9, 0x1f, 0xb6, 0x3b, 0x6e, 0xcb, 0xbe, 0x44, 0x2c, 0xc8, 0xb9, 0x94, 0x1e, 0x53,
	0xdb, 0xc0, 0xe5, 0x81, 0x7b, 0x78, 0x78, 0x6c, 0x67, 0xf0, 0x50, 0xc7, 0xdd, 0x3f, 0xee, 0xb5,
	0x1b, 0x3d, 0xd7, 0xce, 0xe2, 0x4e, 0xb7, 0xd7, 0xa0, 0x3d, 0xdb, 0x24, 0x05, 0xc8, 0xba, 0x9d,
	0x96, 0x9d, 0x43, 0x5d, 0xf3, 0xc0, 0x6d, 0x7e, 0x64, 0xe7, 0x49, 0x11, 0xcc, 0x76, 0xa7, 0xdd,
	0xb3, 0x0b, 0xb8, 0x7a, 0xd8, 0xee, 0xec, 0xdb, 0x45, 0xdc, 0xa6, 0x6e, 0xd7, 0xed, 0xd9, 0x16,
	0x29, 0x43, 0xb1, 0xd1, 0x6a, 0xf5, 0x9b, 0xc7, 0xed, 0x8e, 0x0d, 0x84, 0x40, 0xb5, 0x49, 0xdd,
	0x46, 0xcf, 0xed, 0x37, 0x5a, 0x2d, 0xea, 0x76, 0xbb, 0x76, 0x89, 0xd4, 0xa0, 0xa2, 0x74, 0x5d,
	0xb7, 0x49, 0xdd, 0x9e, 0x5d, 0x46, 0x04, 0x87, 0xed, 0x6e, 0x4f, 0x5a, 0x55, 0x88, 0x0d, 0x65,
	0x21, 0x6a, 0x9b, 0x2a, 0x59, 0x83, 0x92, 0xd0, 0x28, 0x8b, 0x35, 0x52, 0x82, 0x42, 0xb7, 0xbd,
	0xdf, 0xe9, 0xf7, 0x1e, 0xdb, 0x36, 0xee, 0x52, 0xf7, 0xe8, 0xf8, 0x63, 0x57, 0x3a, 0xa8, 0x61,
	0xd8, 0x96, 0x7b, 0xe8, 0xa6, 0xc2, 0x12, 0x0c, 0xab, 0x74, 0xca, 0xc9, 0x3a, 0xda, 0xed, 0xbb,
	0x49, 0x98, 0x0d, 0x52, 0x05, 0x40, 0x85, 0x3a, 0x70, 0x19, 0x93, 0x11, 0x51, 0x8e, 0xba, 0xfb,
	0xf6, 0x15, 0xe7, 0x7d, 0xc8, 0xb9, 0xd3, 0x69, 0x34, 0x25, 0x04, 0xcc, 0x41, 0xe4, 0x33, 0xd1,
	0xea, 0x1c, 0x15, 0x6b, 0x52, 0x87, 0xc2, 0x58, 0x76, 0x74, 0x33, 0x53, 0x37, 0xb6, 0xad, 0xbd,
	0xfc, 0xf3, 0x07, 0xd9, 0xe2, 0xd7, 0x19, 0xaa, 0xd5, 0xce, 0xdd, 0xc5, 0xb4, 0xac, 0x43, 0xf6,
	0x4c, 0x0d, 0xa7, 0x98, 0x14, 0x94, 0x48, 0x15, 0x32, 0x3c, 0x14, 0x33, 0x52, 0xa1, 0x19, 0x1e,
	0x3a, 0xa7, 0x50, 0xa2, 0x6c, 0x32, 0x9a, 0xbf, 0x86, 0xcd, 0x02, 0x58, 0x56, 0x68, 0x5e, 0x00,
	0x66, 0xa6, 0x80, 0x19, 0x09, 0xb0, 0xdb, 0x60, 0x1d, 0x04, 0x94, 0x7d, 0xfe, 0x8c, 0xf1, 0x98,
	0x5c, 0x81, 0xfc, 0xd8, 0x1b, 0x06, 0x83, 0x86, 0x70, 0x9b, 0xa5, 0x4a, 0x72, 0x6e, 0x41, 0x01,
	0x0f, 0x4d, 0x46, 0xf3, 0xc5, 0x91, 0xbd, 0xa5, 0x23, 0x7b, 0xce, 0x7d, 0xb0, 0x3b, 0x6c, 0x18,
	0xc5, 0x81, 0x17, 0x33, 0xed, 0x8e, 0x80, 0xf9, 0x94, 0xcd, 0xa5, 0x33, 0x8b, 0x8a, 0x35, 0xea,
	0x4e, 0x3d, 0x7e, 0x2a, 0x50, 0x5a, 0x54, 0xac, 0x9d, 0xff, 0x43, 0x35, 0x65, 0x8b, 0x51, 0xa4,
	0xe5, 0x5e, 0xca, 0x72, 0xef, 0x5c, 0xcb, 0x2a, 0x94, 0xbb, 0xb1, 0x37, 0x8d, 0x55, 0x44, 0xa7,
	0x0c, 0xa0, 0xe4, 0xc9, 0x68, 0xee, 0x7c, 0x6f, 0xc0, 0x7a, 0x33, 0x0a, 0xf1, 0x2a, 0x7a, 0x71,
	0x10, 0x85, 0x1a, 0xd7, 0xf2, 0x05, 0xca, 0xac, 0x5c, 0x20, 0xdc, 0x56, 0xd5, 0xc1, 0x6d, 0x59,
	0x4e, 0x4b, 0x69, 0xda, 0x3e, 0x32, 0xc6, 0x20, 0x0a, 0x63, 0x16, 0xc6, 0xe2, 0xee, 0x59, 0x54,
	0x8b, 0xcb, 0x8c, 0x91, 0x13, 0x7b, 0x89, 0xc2, 0xf9, 0xd6, 0x80, 0xda, 0x32, 0x1a, 0xcc, 0xf4,
	0xed, 0x60, 0x29, 0x03, 0xb8, 0xa1, 0xaf, 0xab, 0x06, 0x50, 0x14, 0x12, 0xd6, 0xac, 0x0a, 0xe5,
	0xe6, 0x29, 0x1b, 0x3c, 0xd5, 0x7b, 0xef, 0x00, 0x28, 0x19, 0xd1, 0x6e, 0x40, 0x8e, 0xc7, 0x5e,
	0xcc, 0x34, 0x09, 0x0b, 0x81, 0x5c, 0x86, 0xbc, 0xcf, 0xce, 0x24, 0x40, 0x63, 0xdb, 0xa2, 0x39,
	0x9f, 0x9d, 0xb5, 0x7d, 0xe7, 0x1e, 0x94, 0xda, 0x61, 0xa0, 0x7b, 0x43, 0x1c, 0x28, 0x4e, 0x3c,
	0xce, 0xbf, 0x88, 0xa6, 0x32, 0xcf, 0x64, 0x18, 0x17, 0x7a, 0xe7, 0x0e, 0x58, 0xd2, 0x04, 0x83,
	0x5d, 0x5b, 0xb8, 0x95, 0xc7, 0x73, 0xcf, 0x1f, 0x64, 0x8a, 0x75, 0xed, 0xbd, 0x02, 0xa5, 0x87,
	0x41, 0x38, 0xd4, 0x38, 0xef, 0x80, 0x25, 0x45, 0x69, 0x99, 0xe2, 0x52, 0x39, 0xa7, 0x89, 0xc2,
	0x39, 0x81, 0x6a, 0xc3, 0xf7, 0x9b, 0x51, 0x10, 0xa6, 0x06, 0x75, 0x41, 0xd2, 0x15, 0xc5, 0xc7,
	0x36, 0x64, 0x03, 0x7f, 0xa6, 0x4a, 0x8e, 0x4b, 0x1c, 0x7d, 0x3e, 0x1f, 0x9f, 0x44, 0x23, 0x55,
	0x6b, 0x25, 0xa1, 0x75, 0xe8, 0x8d, 0x75, 0x95, 0xc5, 0x1a, 0xcb, 0xb8, 0x88, 0x81, 0x65, 0xed,
	0xc3, 0x46, 0x73, 0xca, 0xbc, 0x98, 0x35, 0x7c, 0x7f, 0xca, 0x38, 0xd7, 0x91, 0x6f, 0xa5, 0x8a,
	0x62, 0x24, 0x59, 0x7e, 0x90, 0xd4, 0xe4, 0xaf, 0xc1, 0x19, 0x0a, 0x9c, 0xf3, 0x19, 0x90, 0x95,
	0x00, 0xea, 0x1e, 0x09, 0x5b, 0xe3, 0x45, 0xdb, 0x4c, 0x92, 0xd8, 0x4d, 0x28, 0x78, 0xd2, 0x4a,
	0x5e, 0x2e, 0x8d, 0x41, 0x6b, 0x9d, 0x2f, 0x61, 0x5d, 0x3a, 0xef, 0xb2, 0xc1, 0x94, 0xc5, 0x17,
	0x04, 0x4f, 0xc0, 0xe4, 0x41, 0xbc, 0x20, 0x2a, 0x5c, 0xe3, 0x20, 0x7b, 0x83, 0x41, 0xf4, 0x4c,
	0x0d, 0x72, 0x85, 0x6a, 0xd1, 0xf9, 0x0e, 0xaf, 0xcd, 0x52, 0xf0, 0x3f, 0x4b, 0x4c, 0xfb, 0xcd,
	0x9c, 0xef, 0x37, 0xbb, 0xe4, 0x17, 0x47, 0x39, 0x08, 0x7d, 0x36, 0x53, 0xf1, 0xa4, 0x40, 0xae,
	0x43, 0x9e, 0x8b, 0x30, 0xb2, 0x9b, 0x3a, 0x21, 0xa5, 0x74, 0x7e, 0x30, 0xc0, 0x6e, 0xf8, 0xfe,
	0x3f, 0x5f, 0x86, 0x97, 0x01, 0xfb, 0xc6, 0x10, 0x43, 0xfd, 0x66, 0x4b, 0xa4, 0x26, 0xc5, 0x4c,
	0x26, 0xe5, 0x25, 0x28, 0x7e, 0x35, 0xa0, 0xd2, 0x0d, 0x86, 0x61, 0x6f, 0xa6, 0x6b, 0xb3, 0xb5,
	0x5a, 0x9b, 0x57, 0x1d, 0xec, 0xf4, 0xad, 0xf3, 0xc6, 0x8b, 0x8a, 0x98, 0x54, 0x49, 0xe4, 0x2a,
	0x98, 0x3e, 0xe3, 0x2b, 0x40, 0x84, 0x8a, 0xdc, 0x80, 0x42, 0x3c, 0xeb, 0x8b, 0x8f, 0x45, 0x7e,
	0x09, 0x66, 0x3c, 0x3b, 0xf0, 0xf8, 0x29, 0xf2, 0x55, 0x3c, 0xeb, 0x63, 0x9c, 0x82, 0xec, 0x7d,
	0x3c, 0x6b, 0xfb, 0x33, 0xe4, 0x2b, 0x0d, 0x1e, 0xeb, 0xe7, 0x40, 0x11, 0x09, 0x93, 0xf9, 0x3d,
	0x79, 0x59, 0xca, 0x8a, 0xaf, 0x4c, 0xba, 0xd0, 0x3b, 0x23, 0xa8, 0xa2, 0xc9, 0x11, 0x1f, 0xbe,
	0xb9, 0x84, 0x37, 0xd3, 0xdf, 0x6c, 0xf1, 0x22, 0xd5, 0xdf, 0xea, 0x1d, 0x28, 0x2f, 0xa2, 0x21,
	0xc2, 0x1b, 0x90, 0x97, 0x48, 0x44, 0xa4, 0x04, 0x9f, 0xd2, 0x3a, 0x35, 0x58, 0x3b, 0x0c, 0x78,
	0x9c, 0x62, 0x3a, 0xe7, 0x3d, 0xa8, 0x24, 0x2a, 0xf4, 0x61, 0x43, 0x76, 0xec, 0x2d, 0xd8, 0x60,
	0xec, 0xcd, 0xb0, 0xb0, 0x02, 0x65, 0xb6, 0x9e, 0xdd, 0xae, 0x88, 0xd2, 0xd9, 0x45, 0x09, 0xd6,
	0x79, 0x04, 0xb5, 0x7d, 0x16, 0xaf, 0x50, 0xd8, 0x85, 0x33, 0x76, 0xfe, 0x07, 0x6b, 0x69, 0xb7,
	0x92, 0xc1, 0x4d, 0x24, 0x1f, 0xf5, 0x86, 0x2f, 0xee, 0xe8, 0x4d, 0xa1, 0x75, 0xa6, 0x40, 0x30,
	0x8b, 0x0b, 0x02, 0xb9, 0x02, 0xf9, 0xe8, 0xc9, 0x13, 0xce, 0xf4, 0xdc, 0x2b, 0x09, 0x99, 0x61,
	0x14, 0x8c, 0x03, 0x7d, 0x05, 0xa5, 0xe0, 0x78, 0x50, 0x50, 0xf1, 0x5e, 0x91, 0x55, 0xf5, 0x67,
	0x41, 0x7e, 0x13, 0xc5, 0x1a, 0x3f, 0x69, 0xbc, 0x2f, 0x12, 0x33, 0xd3, 0x83, 0x99, 0xe3, 0xe8,
	0xda, 0xf9, 0xd9, 0x00, 0x7b, 0x29, 0x2f, 0xac, 0xc4, 0x6d, 0xa8, 0xc4, 0x51, 0xec, 0x8d, 0xfa,
	0x53, 0x36, 0x88, 0xa6, 0xea, 0x77, 0x51, 0x85, 0x96, 0x85, 0x92, 0x4a, 0x1d, 0xb9, 0x09, 0x25,
	0x79, 0x68, 0xe2, 0x0d, 0x19, 0x57, 0x28, 0x40, 0xa8, 0x1e, 0xa2, 0x26, 0xc9, 0x29, 0x9b, 0xca,
	0x29, 0x55, 0x01, 0x73, 0xa9, 0x02, 0xb7, 0x55, 0xf5, 0x73, 0xf5, 0x6c, 0xba, 0xfa, 0x72, 0x18,
	0xae, 0xaa, 0x26, 0xfc, 0x64, 0x40, 0x0d, 0xd1, 0x2e, 0x93, 0xe1, 0xeb, 0x36, 0x21, 0x61, 0x41,
	0xe3, 0x7c, 0x16, 0x34, 0xd2, 0x8c, 0x94, 0x00, 0xce, 0x9d, 0xdf, 0xb2, 0x7c, 0xba, 0x65, 0x5f,
	0x41, 0x5e, 0x82, 0xfb, 0x5b, 0xb8, 0xb0, 0x0e, 0x45, 0xde, 0x3f, 0x8f, 0x0d, 0x0b, 0x5c, 0x46,
	0x75, 0x7e, 0x31, 0xe4, 0x05, 0x4c, 0xb3, 0xf2, 0xdb, 0x68, 0xe7, 0xbf, 0x53, 0xac, 0x8d, 0x0d,
	0x2d, 0xec, 0x48, 0x44, 0xba, 0x9f, 0x9a, 0xbe, 0x9b, 0x50, 0xa3, 0x6c, 0x1c, 0x9d, 0xb1, 0xf4,
	0xdb, 0xe8, 0x35, 0x1b, 0x8a, 0xa4, 0x93, 0x76, 0x82, 0x8f, 0x9f, 0x4f, 0x60, 0xbd, 0xc5, 0x46,
	0x6c, 0xf5, 0xf9, 0x70, 0x71, 0xe2, 0x58, 0x87, 0xda, 0xb2, 0x63, 0x8c, 0xf6, 0x18, 0x36, 0xa4,
	0xf2, 0x8d, 0xf3, 0xd4, 0x06, 0x90, 0x15, 0xcf, 0x18, 0xef, 0xbf, 0x50, 0xa6, 0x8c, 0xbf, 0x52,
	0x5a, 0xf8, 0xee, 0x56, 0x67, 0x27, 0xa3, 0xf9, 0xee, 0x2e, 0xe4, 0xe5, 0xdf, 0x01, 0x64, 0x1b,
	0xcc, 0xe6, 0xa9, 0x17, 0x93, 0xea, 0xf2, 0xff, 0x03, 0x5b, 0x2b, 0xb2, 0x73, 0x69, 0xaf, 0xf8,
	0x69, 0x5e, 0xfc, 0x6d, 0xc2, 0xff, 0x08, 0x00, 0x00, 0xff, 0xff, 0xdf, 0x3c, 0x68, 0x44, 0x54,
	0x11, 0x00, 0x00,
}
