/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.1 at Thu May  3 17:48:49 2018. */

#ifndef PB_ICEBOX_PB_H_INCLUDED
#define PB_ICEBOX_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _IceboxMessage_Type {
    IceboxMessage_Type_UNDEFINED = 0,
    IceboxMessage_Type_ERROR = 1,
    IceboxMessage_Type_HELLO = 2,
    IceboxMessage_Type_NEGOTIATE = 3,
    IceboxMessage_Type_START = 4,
    IceboxMessage_Type_END = 5,
    IceboxMessage_Type_CHECK = 6,
    IceboxMessage_Type_INIT = 7,
    IceboxMessage_Type_PING = 8,
    IceboxMessage_Type_RESET = 9,
    IceboxMessage_Type_ADD_COIN = 10,
    IceboxMessage_Type_CREATE_ADDRESS = 11,
    IceboxMessage_Type_CREATE_SECRET = 12,
    IceboxMessage_Type_LIST_COIN = 13,
    IceboxMessage_Type_LIST_ADDRESS = 14,
    IceboxMessage_Type_LIST_SECRET = 15,
    IceboxMessage_Type_SIGN_TX = 16,
    IceboxMessage_Type_REMOVE_COIN = 17,
    IceboxMessage_Type_DELETE_ADDRESS = 18,
    IceboxMessage_Type_DELETE_SECRET = 19
} IceboxMessage_Type;
#define _IceboxMessage_Type_MIN IceboxMessage_Type_UNDEFINED
#define _IceboxMessage_Type_MAX IceboxMessage_Type_DELETE_SECRET
#define _IceboxMessage_Type_ARRAYSIZE ((IceboxMessage_Type)(IceboxMessage_Type_DELETE_SECRET+1))

/* Struct definitions */
typedef struct _AddCoinReply {
    char dummy_field;
/* @@protoc_insertion_point(struct:AddCoinReply) */
} AddCoinReply;

typedef struct _AddFeatureReply {
    pb_callback_t path;
/* @@protoc_insertion_point(struct:AddFeatureReply) */
} AddFeatureReply;

typedef struct _CheckRequest {
    char dummy_field;
/* @@protoc_insertion_point(struct:CheckRequest) */
} CheckRequest;

typedef struct _DeleteAddressReply {
    char dummy_field;
/* @@protoc_insertion_point(struct:DeleteAddressReply) */
} DeleteAddressReply;

typedef struct _DeleteSecretReply {
    char dummy_field;
/* @@protoc_insertion_point(struct:DeleteSecretReply) */
} DeleteSecretReply;

typedef struct _EndReply {
    char dummy_field;
/* @@protoc_insertion_point(struct:EndReply) */
} EndReply;

typedef struct _EndRequest {
    char dummy_field;
/* @@protoc_insertion_point(struct:EndRequest) */
} EndRequest;

typedef struct _ListCoinRequest {
    char dummy_field;
/* @@protoc_insertion_point(struct:ListCoinRequest) */
} ListCoinRequest;

typedef struct _NegotiateReply {
    pb_callback_t keyB;
    pb_callback_t hash;
/* @@protoc_insertion_point(struct:NegotiateReply) */
} NegotiateReply;

typedef struct _NegotiateRequest {
    pb_callback_t keyA;
    pb_callback_t hash;
/* @@protoc_insertion_point(struct:NegotiateRequest) */
} NegotiateRequest;

typedef struct _PingRequest {
    char dummy_field;
/* @@protoc_insertion_point(struct:PingRequest) */
} PingRequest;

typedef struct _RemoveCoinReply {
    char dummy_field;
/* @@protoc_insertion_point(struct:RemoveCoinReply) */
} RemoveCoinReply;

typedef struct _ResetReply {
    char dummy_field;
/* @@protoc_insertion_point(struct:ResetReply) */
} ResetReply;

typedef struct _ResetRequest {
    pb_callback_t password;
/* @@protoc_insertion_point(struct:ResetRequest) */
} ResetRequest;

typedef struct _StartReply {
    char dummy_field;
/* @@protoc_insertion_point(struct:StartReply) */
} StartReply;

typedef struct _AddCoinRequest {
    uint32_t type;
    uint32_t idx;
    pb_callback_t symbol;
    pb_callback_t name;
/* @@protoc_insertion_point(struct:AddCoinRequest) */
} AddCoinRequest;

typedef struct _AddFeatureRequest {
    uint32_t type;
    uint32_t idx;
    pb_callback_t symbol;
    pb_callback_t name;
/* @@protoc_insertion_point(struct:AddFeatureRequest) */
} AddFeatureRequest;

typedef struct _Address {
    uint32_t type;
    uint32_t idx;
    char s_addr[64];
/* @@protoc_insertion_point(struct:Address) */
} Address;

typedef struct _CheckReply {
    int32_t state;
    pb_callback_t dev_id;
/* @@protoc_insertion_point(struct:CheckReply) */
} CheckReply;

typedef struct _ConversationReply {
    uint32_t session_id;
    uint32_t message_id;
    pb_callback_t content;
    pb_callback_t signature;
/* @@protoc_insertion_point(struct:ConversationReply) */
} ConversationReply;

typedef struct _ConversationRequest {
    uint32_t session_id;
    uint32_t message_id;
    pb_callback_t content;
    pb_callback_t signature;
/* @@protoc_insertion_point(struct:ConversationRequest) */
} ConversationRequest;

typedef struct _CreateAddressReply {
    char address[64];
/* @@protoc_insertion_point(struct:CreateAddressReply) */
} CreateAddressReply;

typedef struct _CreateAddressRequest {
    uint32_t type;
    uint32_t idx;
    char password[64];
    bool has_name;
    char name[32];
/* @@protoc_insertion_point(struct:CreateAddressRequest) */
} CreateAddressRequest;

typedef struct _CreateFormulaReply {
    char result[64];
/* @@protoc_insertion_point(struct:CreateFormulaReply) */
} CreateFormulaReply;

typedef struct _CreateFormulaRequest {
    uint32_t iscoin;
    uint32_t type;
    uint32_t idx;
    bool has_name;
    char name[32];
/* @@protoc_insertion_point(struct:CreateFormulaRequest) */
} CreateFormulaRequest;

typedef struct _CreateSecretReply {
    char address[64];
/* @@protoc_insertion_point(struct:CreateSecretReply) */
} CreateSecretReply;

typedef struct _CreateSecretRequest {
    uint32_t type;
    uint32_t idx;
    char password[64];
    bool has_name;
    char name[32];
/* @@protoc_insertion_point(struct:CreateSecretRequest) */
} CreateSecretRequest;

typedef struct _DeleteAddressRequest {
    pb_callback_t password;
    uint32_t type;
    uint32_t idx;
/* @@protoc_insertion_point(struct:DeleteAddressRequest) */
} DeleteAddressRequest;

typedef struct _DeleteSecretRequest {
    pb_callback_t password;
    uint32_t type;
    uint32_t idx;
/* @@protoc_insertion_point(struct:DeleteSecretRequest) */
} DeleteSecretRequest;

typedef struct _Error {
    int32_t code;
    bool has_message;
    char message[256];
/* @@protoc_insertion_point(struct:Error) */
} Error;

typedef struct _Header {
    uint32_t ver;
    uint32_t sn;
/* @@protoc_insertion_point(struct:Header) */
} Header;

typedef struct _HiReply {
    int64_t magicB;
/* @@protoc_insertion_point(struct:HiReply) */
} HiReply;

typedef struct _HiRequest {
    int64_t magicA;
/* @@protoc_insertion_point(struct:HiRequest) */
} HiRequest;

typedef struct _IceboxMessage {
    uint32_t version;
    IceboxMessage_Type type;
    uint32_t session_id;
    pb_callback_t payload;
    pb_callback_t signature;
/* @@protoc_insertion_point(struct:IceboxMessage) */
} IceboxMessage;

typedef struct _InitReply {
    char dev_id[32];
/* @@protoc_insertion_point(struct:InitReply) */
} InitReply;

typedef struct _InitRequest {
    char password[128];
/* @@protoc_insertion_point(struct:InitRequest) */
} InitRequest;

typedef struct _ListAddressRequest {
    pb_callback_t password;
    uint32_t type;
    bool has_idx;
    uint32_t idx;
/* @@protoc_insertion_point(struct:ListAddressRequest) */
} ListAddressRequest;

typedef struct _ListCoinReply {
    uint32_t max;
    pb_size_t type_count;
    uint32_t type[8];
/* @@protoc_insertion_point(struct:ListCoinReply) */
} ListCoinReply;

typedef struct _ListSecretRequest {
    uint32_t type;
    bool has_idx;
    uint32_t idx;
/* @@protoc_insertion_point(struct:ListSecretRequest) */
} ListSecretRequest;

typedef struct _PingReply {
    int64_t timestamp;
/* @@protoc_insertion_point(struct:PingReply) */
} PingReply;

typedef struct _RemoveCoinRequest {
    pb_callback_t password;
    uint32_t type;
/* @@protoc_insertion_point(struct:RemoveCoinRequest) */
} RemoveCoinRequest;

typedef struct _ReplyHeader {
    uint32_t ver;
    uint32_t sn;
    uint32_t code;
    bool has_message;
    char message[128];
/* @@protoc_insertion_point(struct:ReplyHeader) */
} ReplyHeader;

typedef struct _Secret {
    uint32_t type;
    uint32_t idx;
    char s_addr[64];
/* @@protoc_insertion_point(struct:Secret) */
} Secret;

typedef struct _SignTxReply {
    char signedTx[256];
/* @@protoc_insertion_point(struct:SignTxReply) */
} SignTxReply;

typedef struct _SignTxRequest {
    pb_callback_t password;
    uint32_t type;
    uint32_t idx;
    uint64_t amount;
    char dest[64];
    char txid[64];
/* @@protoc_insertion_point(struct:SignTxRequest) */
} SignTxRequest;

typedef struct _StartRequest {
    uint32_t sessionID;
    uint32_t duration;
/* @@protoc_insertion_point(struct:StartRequest) */
} StartRequest;

typedef struct _ListAddressReply {
    uint32_t max;
    pb_size_t addr_count;
    Address addr[8];
/* @@protoc_insertion_point(struct:ListAddressReply) */
} ListAddressReply;

typedef struct _ListSecretReply {
    uint32_t max;
    pb_size_t secret_count;
    Secret secret[8];
/* @@protoc_insertion_point(struct:ListSecretReply) */
} ListSecretReply;

/* Default values for struct fields */
extern const uint32_t IceboxMessage_version_default;
extern const uint32_t Header_ver_default;
extern const uint32_t ReplyHeader_ver_default;
extern const uint32_t CreateFormulaRequest_iscoin_default;

/* Initializer values for message structs */
#define IceboxMessage_init_default               {1u, _IceboxMessage_Type_MIN, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define Error_init_default                       {0, false, ""}
#define Header_init_default                      {1u, 0}
#define ReplyHeader_init_default                 {1u, 0, 0, false, ""}
#define HiRequest_init_default                   {0}
#define HiReply_init_default                     {0}
#define NegotiateRequest_init_default            {{{NULL}, NULL}, {{NULL}, NULL}}
#define NegotiateReply_init_default              {{{NULL}, NULL}, {{NULL}, NULL}}
#define StartRequest_init_default                {0, 0}
#define StartReply_init_default                  {0}
#define ConversationRequest_init_default         {0, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define ConversationReply_init_default           {0, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define EndRequest_init_default                  {0}
#define EndReply_init_default                    {0}
#define CheckRequest_init_default                {0}
#define CheckReply_init_default                  {0, {{NULL}, NULL}}
#define InitRequest_init_default                 {""}
#define InitReply_init_default                   {""}
#define PingRequest_init_default                 {0}
#define PingReply_init_default                   {0}
#define AddFeatureRequest_init_default           {0, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define AddFeatureReply_init_default             {{{NULL}, NULL}}
#define AddCoinRequest_init_default              {0, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define AddCoinReply_init_default                {0}
#define CreateFormulaRequest_init_default        {1u, 0, 0, false, ""}
#define CreateFormulaReply_init_default          {""}
#define CreateAddressRequest_init_default        {0, 0, "", false, ""}
#define CreateAddressReply_init_default          {""}
#define CreateSecretRequest_init_default         {0, 0, "", false, ""}
#define CreateSecretReply_init_default           {""}
#define SignTxRequest_init_default               {{{NULL}, NULL}, 0, 0, 0, "", ""}
#define SignTxReply_init_default                 {""}
#define ListCoinRequest_init_default             {0}
#define ListCoinReply_init_default               {0, 0, {0, 0, 0, 0, 0, 0, 0, 0}}
#define ListSecretRequest_init_default           {0, false, 0}
#define Secret_init_default                      {0, 0, ""}
#define ListSecretReply_init_default             {0, 0, {Secret_init_default, Secret_init_default, Secret_init_default, Secret_init_default, Secret_init_default, Secret_init_default, Secret_init_default, Secret_init_default}}
#define ListAddressRequest_init_default          {{{NULL}, NULL}, 0, false, 0}
#define Address_init_default                     {0, 0, ""}
#define ListAddressReply_init_default            {0, 0, {Address_init_default, Address_init_default, Address_init_default, Address_init_default, Address_init_default, Address_init_default, Address_init_default, Address_init_default}}
#define RemoveCoinRequest_init_default           {{{NULL}, NULL}, 0}
#define RemoveCoinReply_init_default             {0}
#define DeleteSecretRequest_init_default         {{{NULL}, NULL}, 0, 0}
#define DeleteSecretReply_init_default           {0}
#define DeleteAddressRequest_init_default        {{{NULL}, NULL}, 0, 0}
#define DeleteAddressReply_init_default          {0}
#define ResetRequest_init_default                {{{NULL}, NULL}}
#define ResetReply_init_default                  {0}
#define IceboxMessage_init_zero                  {0, _IceboxMessage_Type_MIN, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define Error_init_zero                          {0, false, ""}
#define Header_init_zero                         {0, 0}
#define ReplyHeader_init_zero                    {0, 0, 0, false, ""}
#define HiRequest_init_zero                      {0}
#define HiReply_init_zero                        {0}
#define NegotiateRequest_init_zero               {{{NULL}, NULL}, {{NULL}, NULL}}
#define NegotiateReply_init_zero                 {{{NULL}, NULL}, {{NULL}, NULL}}
#define StartRequest_init_zero                   {0, 0}
#define StartReply_init_zero                     {0}
#define ConversationRequest_init_zero            {0, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define ConversationReply_init_zero              {0, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define EndRequest_init_zero                     {0}
#define EndReply_init_zero                       {0}
#define CheckRequest_init_zero                   {0}
#define CheckReply_init_zero                     {0, {{NULL}, NULL}}
#define InitRequest_init_zero                    {""}
#define InitReply_init_zero                      {""}
#define PingRequest_init_zero                    {0}
#define PingReply_init_zero                      {0}
#define AddFeatureRequest_init_zero              {0, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define AddFeatureReply_init_zero                {{{NULL}, NULL}}
#define AddCoinRequest_init_zero                 {0, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define AddCoinReply_init_zero                   {0}
#define CreateFormulaRequest_init_zero           {0, 0, 0, false, ""}
#define CreateFormulaReply_init_zero             {""}
#define CreateAddressRequest_init_zero           {0, 0, "", false, ""}
#define CreateAddressReply_init_zero             {""}
#define CreateSecretRequest_init_zero            {0, 0, "", false, ""}
#define CreateSecretReply_init_zero              {""}
#define SignTxRequest_init_zero                  {{{NULL}, NULL}, 0, 0, 0, "", ""}
#define SignTxReply_init_zero                    {""}
#define ListCoinRequest_init_zero                {0}
#define ListCoinReply_init_zero                  {0, 0, {0, 0, 0, 0, 0, 0, 0, 0}}
#define ListSecretRequest_init_zero              {0, false, 0}
#define Secret_init_zero                         {0, 0, ""}
#define ListSecretReply_init_zero                {0, 0, {Secret_init_zero, Secret_init_zero, Secret_init_zero, Secret_init_zero, Secret_init_zero, Secret_init_zero, Secret_init_zero, Secret_init_zero}}
#define ListAddressRequest_init_zero             {{{NULL}, NULL}, 0, false, 0}
#define Address_init_zero                        {0, 0, ""}
#define ListAddressReply_init_zero               {0, 0, {Address_init_zero, Address_init_zero, Address_init_zero, Address_init_zero, Address_init_zero, Address_init_zero, Address_init_zero, Address_init_zero}}
#define RemoveCoinRequest_init_zero              {{{NULL}, NULL}, 0}
#define RemoveCoinReply_init_zero                {0}
#define DeleteSecretRequest_init_zero            {{{NULL}, NULL}, 0, 0}
#define DeleteSecretReply_init_zero              {0}
#define DeleteAddressRequest_init_zero           {{{NULL}, NULL}, 0, 0}
#define DeleteAddressReply_init_zero             {0}
#define ResetRequest_init_zero                   {{{NULL}, NULL}}
#define ResetReply_init_zero                     {0}

/* Field tags (for use in manual encoding/decoding) */
#define AddFeatureReply_path_tag                 2
#define NegotiateReply_keyB_tag                  2
#define NegotiateReply_hash_tag                  3
#define NegotiateRequest_keyA_tag                2
#define NegotiateRequest_hash_tag                3
#define ResetRequest_password_tag                1
#define AddCoinRequest_type_tag                  2
#define AddCoinRequest_idx_tag                   3
#define AddCoinRequest_symbol_tag                4
#define AddCoinRequest_name_tag                  5
#define AddFeatureRequest_type_tag               2
#define AddFeatureRequest_idx_tag                3
#define AddFeatureRequest_symbol_tag             4
#define AddFeatureRequest_name_tag               5
#define Address_type_tag                         1
#define Address_idx_tag                          2
#define Address_s_addr_tag                       3
#define CheckReply_state_tag                     2
#define CheckReply_dev_id_tag                    3
#define ConversationReply_session_id_tag         2
#define ConversationReply_message_id_tag         3
#define ConversationReply_content_tag            4
#define ConversationReply_signature_tag          5
#define ConversationRequest_session_id_tag       2
#define ConversationRequest_message_id_tag       3
#define ConversationRequest_content_tag          4
#define ConversationRequest_signature_tag        5
#define CreateAddressReply_address_tag           2
#define CreateAddressRequest_type_tag            2
#define CreateAddressRequest_idx_tag             3
#define CreateAddressRequest_password_tag        4
#define CreateAddressRequest_name_tag            5
#define CreateFormulaReply_result_tag            2
#define CreateFormulaRequest_iscoin_tag          2
#define CreateFormulaRequest_type_tag            3
#define CreateFormulaRequest_idx_tag             4
#define CreateFormulaRequest_name_tag            5
#define CreateSecretReply_address_tag            2
#define CreateSecretRequest_type_tag             2
#define CreateSecretRequest_idx_tag              3
#define CreateSecretRequest_password_tag         4
#define CreateSecretRequest_name_tag             5
#define DeleteAddressRequest_password_tag        1
#define DeleteAddressRequest_type_tag            2
#define DeleteAddressRequest_idx_tag             3
#define DeleteSecretRequest_password_tag         1
#define DeleteSecretRequest_type_tag             2
#define DeleteSecretRequest_idx_tag              3
#define Error_code_tag                           1
#define Error_message_tag                        2
#define Header_ver_tag                           1
#define Header_sn_tag                            2
#define HiReply_magicB_tag                       2
#define HiRequest_magicA_tag                     2
#define IceboxMessage_version_tag                1
#define IceboxMessage_type_tag                   2
#define IceboxMessage_session_id_tag             3
#define IceboxMessage_payload_tag                4
#define IceboxMessage_signature_tag              5
#define InitReply_dev_id_tag                     2
#define InitRequest_password_tag                 2
#define ListAddressRequest_password_tag          1
#define ListAddressRequest_type_tag              2
#define ListAddressRequest_idx_tag               3
#define ListCoinReply_max_tag                    2
#define ListCoinReply_type_tag                   3
#define ListSecretRequest_type_tag               2
#define ListSecretRequest_idx_tag                3
#define PingReply_timestamp_tag                  2
#define RemoveCoinRequest_password_tag           1
#define RemoveCoinRequest_type_tag               2
#define ReplyHeader_ver_tag                      1
#define ReplyHeader_sn_tag                       2
#define ReplyHeader_code_tag                     3
#define ReplyHeader_message_tag                  4
#define Secret_type_tag                          1
#define Secret_idx_tag                           2
#define Secret_s_addr_tag                        3
#define SignTxReply_signedTx_tag                 2
#define SignTxRequest_password_tag               1
#define SignTxRequest_type_tag                   2
#define SignTxRequest_idx_tag                    3
#define SignTxRequest_amount_tag                 4
#define SignTxRequest_dest_tag                   5
#define SignTxRequest_txid_tag                   6
#define StartRequest_sessionID_tag               2
#define StartRequest_duration_tag                3
#define ListAddressReply_max_tag                 2
#define ListAddressReply_addr_tag                3
#define ListSecretReply_max_tag                  2
#define ListSecretReply_secret_tag               3

/* Struct field encoding specification for nanopb */
extern const pb_field_t IceboxMessage_fields[6];
extern const pb_field_t Error_fields[3];
extern const pb_field_t Header_fields[3];
extern const pb_field_t ReplyHeader_fields[5];
extern const pb_field_t HiRequest_fields[2];
extern const pb_field_t HiReply_fields[2];
extern const pb_field_t NegotiateRequest_fields[3];
extern const pb_field_t NegotiateReply_fields[3];
extern const pb_field_t StartRequest_fields[3];
extern const pb_field_t StartReply_fields[1];
extern const pb_field_t ConversationRequest_fields[5];
extern const pb_field_t ConversationReply_fields[5];
extern const pb_field_t EndRequest_fields[1];
extern const pb_field_t EndReply_fields[1];
extern const pb_field_t CheckRequest_fields[1];
extern const pb_field_t CheckReply_fields[3];
extern const pb_field_t InitRequest_fields[2];
extern const pb_field_t InitReply_fields[2];
extern const pb_field_t PingRequest_fields[1];
extern const pb_field_t PingReply_fields[2];
extern const pb_field_t AddFeatureRequest_fields[5];
extern const pb_field_t AddFeatureReply_fields[2];
extern const pb_field_t AddCoinRequest_fields[5];
extern const pb_field_t AddCoinReply_fields[1];
extern const pb_field_t CreateFormulaRequest_fields[5];
extern const pb_field_t CreateFormulaReply_fields[2];
extern const pb_field_t CreateAddressRequest_fields[5];
extern const pb_field_t CreateAddressReply_fields[2];
extern const pb_field_t CreateSecretRequest_fields[5];
extern const pb_field_t CreateSecretReply_fields[2];
extern const pb_field_t SignTxRequest_fields[7];
extern const pb_field_t SignTxReply_fields[2];
extern const pb_field_t ListCoinRequest_fields[1];
extern const pb_field_t ListCoinReply_fields[3];
extern const pb_field_t ListSecretRequest_fields[3];
extern const pb_field_t Secret_fields[4];
extern const pb_field_t ListSecretReply_fields[3];
extern const pb_field_t ListAddressRequest_fields[4];
extern const pb_field_t Address_fields[4];
extern const pb_field_t ListAddressReply_fields[3];
extern const pb_field_t RemoveCoinRequest_fields[3];
extern const pb_field_t RemoveCoinReply_fields[1];
extern const pb_field_t DeleteSecretRequest_fields[4];
extern const pb_field_t DeleteSecretReply_fields[1];
extern const pb_field_t DeleteAddressRequest_fields[4];
extern const pb_field_t DeleteAddressReply_fields[1];
extern const pb_field_t ResetRequest_fields[2];
extern const pb_field_t ResetReply_fields[1];

/* Maximum encoded size of messages (where known) */
/* IceboxMessage_size depends on runtime parameters */
#define Error_size                               270
#define Header_size                              12
#define ReplyHeader_size                         149
#define HiRequest_size                           11
#define HiReply_size                             11
/* NegotiateRequest_size depends on runtime parameters */
/* NegotiateReply_size depends on runtime parameters */
#define StartRequest_size                        12
#define StartReply_size                          0
/* ConversationRequest_size depends on runtime parameters */
/* ConversationReply_size depends on runtime parameters */
#define EndRequest_size                          0
#define EndReply_size                            0
#define CheckRequest_size                        0
/* CheckReply_size depends on runtime parameters */
#define InitRequest_size                         131
#define InitReply_size                           34
#define PingRequest_size                         0
#define PingReply_size                           11
/* AddFeatureRequest_size depends on runtime parameters */
/* AddFeatureReply_size depends on runtime parameters */
/* AddCoinRequest_size depends on runtime parameters */
#define AddCoinReply_size                        0
#define CreateFormulaRequest_size                52
#define CreateFormulaReply_size                  66
#define CreateAddressRequest_size                112
#define CreateAddressReply_size                  66
#define CreateSecretRequest_size                 112
#define CreateSecretReply_size                   66
/* SignTxRequest_size depends on runtime parameters */
#define SignTxReply_size                         259
#define ListCoinRequest_size                     0
#define ListCoinReply_size                       54
#define ListSecretRequest_size                   12
#define Secret_size                              78
#define ListSecretReply_size                     646
/* ListAddressRequest_size depends on runtime parameters */
#define Address_size                             78
#define ListAddressReply_size                    646
/* RemoveCoinRequest_size depends on runtime parameters */
#define RemoveCoinReply_size                     0
/* DeleteSecretRequest_size depends on runtime parameters */
#define DeleteSecretReply_size                   0
/* DeleteAddressRequest_size depends on runtime parameters */
#define DeleteAddressReply_size                  0
/* ResetRequest_size depends on runtime parameters */
#define ResetReply_size                          0

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define ICEBOX_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
