// Code generated by go-enum
// DO NOT EDIT!

package coins

import (
	"fmt"
	"strings"
)

const (
	// BTC is a Coin of type BTC
	BTC Coin = iota
	// TEST is a Coin of type TEST
	TEST
	// LTC is a Coin of type LTC
	LTC
	// DOGE is a Coin of type DOGE
	DOGE
	// RDD is a Coin of type RDD
	RDD
	// DSH is a Coin of type DSH
	DSH
	// PPC is a Coin of type PPC
	PPC
	// NMC is a Coin of type NMC
	NMC
	// FTC is a Coin of type FTC
	FTC
	// XCP is a Coin of type XCP
	XCP
	// BLK is a Coin of type BLK
	BLK
	// NSR is a Coin of type NSR
	NSR
	// NBT is a Coin of type NBT
	NBT
	// MZC is a Coin of type MZC
	MZC
	// VIA is a Coin of type VIA
	VIA
	// XCH is a Coin of type XCH
	XCH
	// RBY is a Coin of type RBY
	RBY
	// GRS is a Coin of type GRS
	GRS
	// DGC is a Coin of type DGC
	DGC
	// CCN is a Coin of type CCN
	CCN
	// DGB is a Coin of type DGB
	DGB
	// MONA is a Coin of type MONA
	MONA Coin = iota + 1
	// CLAM is a Coin of type CLAM
	CLAM Coin = iota + 1
	// XPM is a Coin of type XPM
	XPM Coin = iota + 1
	// NEOS is a Coin of type NEOS
	NEOS Coin = iota + 1
	// JBS is a Coin of type JBS
	JBS Coin = iota + 1
	// ZRC is a Coin of type ZRC
	ZRC Coin = iota + 1
	// VTC is a Coin of type VTC
	VTC Coin = iota + 1
	// NXT is a Coin of type NXT
	NXT Coin = iota + 1
	// BURST is a Coin of type BURST
	BURST Coin = iota + 1
	// MUE is a Coin of type MUE
	MUE Coin = iota + 1
	// ZOOM is a Coin of type ZOOM
	ZOOM Coin = iota + 1
	// VPN is a Coin of type VPN
	VPN Coin = iota + 1
	// CDN is a Coin of type CDN
	CDN Coin = iota + 1
	// SDC is a Coin of type SDC
	SDC Coin = iota + 1
	// PKB is a Coin of type PKB
	PKB Coin = iota + 1
	// PND is a Coin of type PND
	PND Coin = iota + 1
	// START is a Coin of type START
	START Coin = iota + 1
	// MOIN is a Coin of type MOIN
	MOIN Coin = iota + 1
	// EXP is a Coin of type EXP
	EXP Coin = iota + 1
	// EMC2 is a Coin of type EMC2
	EMC2 Coin = iota + 1
	// DCR is a Coin of type DCR
	DCR Coin = iota + 1
	// XEM is a Coin of type XEM
	XEM Coin = iota + 1
	// PART is a Coin of type PART
	PART Coin = iota + 1
	// ARG is a Coin of type ARG
	ARG Coin = iota + 1
	// SHR is a Coin of type SHR
	SHR Coin = iota + 3
	// GCR is a Coin of type GCR
	GCR Coin = iota + 3
	// NVC is a Coin of type NVC
	NVC Coin = iota + 3
	// AC is a Coin of type AC
	AC Coin = iota + 3
	// BTCD is a Coin of type BTCD
	BTCD Coin = iota + 3
	// DOPE is a Coin of type DOPE
	DOPE Coin = iota + 3
	// TPC is a Coin of type TPC
	TPC Coin = iota + 3
	// AIB is a Coin of type AIB
	AIB Coin = iota + 3
	// EDRC is a Coin of type EDRC
	EDRC Coin = iota + 3
	// SYS is a Coin of type SYS
	SYS Coin = iota + 3
	// SLR is a Coin of type SLR
	SLR Coin = iota + 3
	// SMLY is a Coin of type SMLY
	SMLY Coin = iota + 3
	// ETH is a Coin of type ETH
	ETH Coin = iota + 3
	// ETC is a Coin of type ETC
	ETC Coin = iota + 3
	// PSB is a Coin of type PSB
	PSB Coin = iota + 3
	// LDCN is a Coin of type LDCN
	LDCN Coin = iota + 3
	// XBC is a Coin of type XBC
	XBC Coin = iota + 4
	// IOP is a Coin of type IOP
	IOP Coin = iota + 4
	// NXS is a Coin of type NXS
	NXS Coin = iota + 4
	// INSN is a Coin of type INSN
	INSN Coin = iota + 4
	// OK is a Coin of type OK
	OK Coin = iota + 4
	// BRIT is a Coin of type BRIT
	BRIT Coin = iota + 4
	// CMP is a Coin of type CMP
	CMP Coin = iota + 4
	// CRW is a Coin of type CRW
	CRW Coin = iota + 4
	// BELA is a Coin of type BELA
	BELA Coin = iota + 4
	// VASH is a Coin of type VASH
	VASH Coin = iota + 4
	// FJC is a Coin of type FJC
	FJC Coin = iota + 4
	// MIX is a Coin of type MIX
	MIX Coin = iota + 4
	// XVG is a Coin of type XVG
	XVG Coin = iota + 4
	// EFL is a Coin of type EFL
	EFL Coin = iota + 4
	// CLUB is a Coin of type CLUB
	CLUB Coin = iota + 4
	// RICHX is a Coin of type RICHX
	RICHX Coin = iota + 4
	// POT is a Coin of type POT
	POT Coin = iota + 4
	// QRK is a Coin of type QRK
	QRK Coin = iota + 4
	// TRC is a Coin of type TRC
	TRC Coin = iota + 4
	// GRC is a Coin of type GRC
	GRC Coin = iota + 4
	// AUR is a Coin of type AUR
	AUR Coin = iota + 4
	// IXC is a Coin of type IXC
	IXC Coin = iota + 4
	// NLG is a Coin of type NLG
	NLG Coin = iota + 4
	// BITB is a Coin of type BITB
	BITB Coin = iota + 4
	// BTA is a Coin of type BTA
	BTA Coin = iota + 4
	// XMY is a Coin of type XMY
	XMY Coin = iota + 4
	// BSD is a Coin of type BSD
	BSD Coin = iota + 4
	// UNO is a Coin of type UNO
	UNO Coin = iota + 4
	// MTR is a Coin of type MTR
	MTR Coin = iota + 4
	// GB is a Coin of type GB
	GB Coin = iota + 4
	// SHM is a Coin of type SHM
	SHM Coin = iota + 4
	// CRX is a Coin of type CRX
	CRX Coin = iota + 4
	// BIQ is a Coin of type BIQ
	BIQ Coin = iota + 4
	// EVO is a Coin of type EVO
	EVO Coin = iota + 4
	// STO is a Coin of type STO
	STO Coin = iota + 4
	// BIGUP is a Coin of type BIGUP
	BIGUP Coin = iota + 4
	// GAME is a Coin of type GAME
	GAME Coin = iota + 4
	// DLC is a Coin of type DLC
	DLC Coin = iota + 4
	// ZYD is a Coin of type ZYD
	ZYD Coin = iota + 4
	// DBIC is a Coin of type DBIC
	DBIC Coin = iota + 4
	// STRAT is a Coin of type STRAT
	STRAT Coin = iota + 4
	// SH is a Coin of type SH
	SH Coin = iota + 4
	// MARS is a Coin of type MARS
	MARS Coin = iota + 4
	// UBQ is a Coin of type UBQ
	UBQ Coin = iota + 4
	// PTC is a Coin of type PTC
	PTC Coin = iota + 4
	// NRO is a Coin of type NRO
	NRO Coin = iota + 4
	// ARK is a Coin of type ARK
	ARK Coin = iota + 4
	// USC is a Coin of type USC
	USC Coin = iota + 4
	// THC is a Coin of type THC
	THC Coin = iota + 4
	// LINX is a Coin of type LINX
	LINX Coin = iota + 4
	// ECN is a Coin of type ECN
	ECN Coin = iota + 4
	// DNR is a Coin of type DNR
	DNR Coin = iota + 4
	// PINK is a Coin of type PINK
	PINK Coin = iota + 4
	// PIGGY is a Coin of type PIGGY
	PIGGY Coin = iota + 4
	// PIVX is a Coin of type PIVX
	PIVX Coin = iota + 4
	// FLASH is a Coin of type FLASH
	FLASH Coin = iota + 4
	// ZEN is a Coin of type ZEN
	ZEN Coin = iota + 4
	// PUT is a Coin of type PUT
	PUT Coin = iota + 4
	// ZNY is a Coin of type ZNY
	ZNY Coin = iota + 4
	// UNIFY is a Coin of type UNIFY
	UNIFY Coin = iota + 4
	// XST is a Coin of type XST
	XST Coin = iota + 4
	// BRK is a Coin of type BRK
	BRK Coin = iota + 4
	// VC is a Coin of type VC
	VC Coin = iota + 4
	// XMR is a Coin of type XMR
	XMR Coin = iota + 4
	// VOX is a Coin of type VOX
	VOX Coin = iota + 4
	// NAV is a Coin of type NAV
	NAV Coin = iota + 4
	// FCT is a Coin of type FCT
	FCT Coin = iota + 4
	// EC is a Coin of type EC
	EC Coin = iota + 4
	// ZEC is a Coin of type ZEC
	ZEC Coin = iota + 4
	// LSK is a Coin of type LSK
	LSK Coin = iota + 4
	// STEEM is a Coin of type STEEM
	STEEM Coin = iota + 4
	// XZC is a Coin of type XZC
	XZC Coin = iota + 4
	// SBTC is a Coin of type SBTC
	SBTC Coin = iota + 4
	// RPT is a Coin of type RPT
	RPT Coin = iota + 5
	// LBC is a Coin of type LBC
	LBC Coin = iota + 5
	// KMD is a Coin of type KMD
	KMD Coin = iota + 5
	// BSQ is a Coin of type BSQ
	BSQ Coin = iota + 5
	// RIC is a Coin of type RIC
	RIC Coin = iota + 5
	// XRP is a Coin of type XRP
	XRP Coin = iota + 5
	// BCH is a Coin of type BCH
	BCH Coin = iota + 5
	// NEBL is a Coin of type NEBL
	NEBL Coin = iota + 5
	// ZCL is a Coin of type ZCL
	ZCL Coin = iota + 5
	// XLM is a Coin of type XLM
	XLM Coin = iota + 5
	// NLC2 is a Coin of type NLC2
	NLC2 Coin = iota + 5
	// WHL is a Coin of type WHL
	WHL Coin = iota + 5
	// ERC is a Coin of type ERC
	ERC Coin = iota + 5
	// DMD is a Coin of type DMD
	DMD Coin = iota + 5
	// BTM is a Coin of type BTM
	BTM Coin = iota + 5
	// BIO is a Coin of type BIO
	BIO Coin = iota + 5
	// XWC is a Coin of type XWC
	XWC Coin = iota + 5
	// BTG is a Coin of type BTG
	BTG Coin = iota + 5
	// BTC2X is a Coin of type BTC2X
	BTC2X Coin = iota + 5
	// SSN is a Coin of type SSN
	SSN Coin = iota + 5
	// TOA is a Coin of type TOA
	TOA Coin = iota + 5
	// BTX is a Coin of type BTX
	BTX Coin = iota + 5
	// ACC is a Coin of type ACC
	ACC Coin = iota + 5
	// BCO is a Coin of type BCO
	BCO Coin = iota + 5
	// ELLA is a Coin of type ELLA
	ELLA Coin = iota + 5
	// PIRL is a Coin of type PIRL
	PIRL Coin = iota + 5
	// XRB is a Coin of type XRB
	XRB Coin = iota + 5
	// VIVO is a Coin of type VIVO
	VIVO Coin = iota + 5
	// FRST is a Coin of type FRST
	FRST Coin = iota + 5
	// HNC is a Coin of type HNC
	HNC Coin = iota + 5
	// BUZZ is a Coin of type BUZZ
	BUZZ Coin = iota + 5
	// MBRS is a Coin of type MBRS
	MBRS Coin = iota + 5
	// HSR is a Coin of type HSR
	HSR Coin = iota + 5
	// HTML is a Coin of type HTML
	HTML Coin = iota + 5
	// ODN is a Coin of type ODN
	ODN Coin = iota + 5
	// ONX is a Coin of type ONX
	ONX Coin = iota + 5
	// RVN is a Coin of type RVN
	RVN Coin = iota + 5
	// GBX is a Coin of type GBX
	GBX Coin = iota + 5
	// BTCZ is a Coin of type BTCZ
	BTCZ Coin = iota + 5
	// POA is a Coin of type POA
	POA Coin = iota + 5
	// NYC is a Coin of type NYC
	NYC Coin = iota + 5
	// MXT is a Coin of type MXT
	MXT Coin = iota + 5
	// WC is a Coin of type WC
	WC Coin = iota + 5
	// MNX is a Coin of type MNX
	MNX Coin = iota + 5
	// BTCP is a Coin of type BTCP
	BTCP Coin = iota + 5
	// MUSIC is a Coin of type MUSIC
	MUSIC Coin = iota + 5
	// BCA is a Coin of type BCA
	BCA Coin = iota + 5
	// CRAVE is a Coin of type CRAVE
	CRAVE Coin = iota + 5
	// STAK is a Coin of type STAK
	STAK Coin = iota + 5
	// WBTC is a Coin of type WBTC
	WBTC Coin = iota + 5
	// LCH is a Coin of type LCH
	LCH Coin = iota + 5
	// EXCL is a Coin of type EXCL
	EXCL Coin = iota + 5
	// LCC is a Coin of type LCC
	LCC Coin = iota + 6
	// XFE is a Coin of type XFE
	XFE Coin = iota + 6
	// EOS is a Coin of type EOS
	EOS Coin = iota + 6
	// TRX is a Coin of type TRX
	TRX Coin = iota + 6
	// KOBO is a Coin of type KOBO
	KOBO Coin = iota + 6
	// HUSH is a Coin of type HUSH
	HUSH Coin = iota + 6
	// BANANO is a Coin of type BANANO
	BANANO Coin = iota + 6
	// ETF is a Coin of type ETF
	ETF Coin = iota + 6
	// OMNI is a Coin of type OMNI
	OMNI Coin = iota + 6
	// BIFI is a Coin of type BIFI
	BIFI Coin = iota + 6
	// UFO is a Coin of type UFO
	UFO Coin = iota + 6
	// BIS is a Coin of type BIS
	BIS Coin = iota + 12
	// NEET is a Coin of type NEET
	NEET Coin = iota + 12
	// BOPO is a Coin of type BOPO
	BOPO Coin = iota + 12
	// BOXY is a Coin of type BOXY
	BOXY Coin = iota + 15
	// BITG is a Coin of type BITG
	BITG Coin = iota + 21
	// ASK is a Coin of type ASK
	ASK Coin = iota + 21
	// SMART is a Coin of type SMART
	SMART Coin = iota + 21
	// XUEZ is a Coin of type XUEZ
	XUEZ Coin = iota + 21
	// VAR is a Coin of type VAR
	VAR Coin = iota + 28
	// UC is a Coin of type UC
	UC Coin = iota + 41
	// NANO is a Coin of type NANO
	NANO Coin = iota + 49
	// ARA is a Coin of type ARA
	ARA Coin = iota + 104
	// RAP is a Coin of type RAP
	RAP Coin = iota + 112
	// BLOCK is a Coin of type BLOCK
	BLOCK Coin = iota + 118
	// MEM is a Coin of type MEM
	MEM Coin = iota + 122
	// PHR is a Coin of type PHR
	PHR Coin = iota + 232
	// KOTO is a Coin of type KOTO
	KOTO Coin = iota + 297
	// XRD is a Coin of type XRD
	XRD Coin = iota + 298
	// BCS is a Coin of type BCS
	BCS Coin = iota + 340
	// ACT is a Coin of type ACT
	ACT Coin = iota + 450
	// SSC is a Coin of type SSC
	SSC Coin = iota + 451
	// BTW is a Coin of type BTW
	BTW Coin = iota + 559
	// BEET is a Coin of type BEET
	BEET Coin = iota + 581
	// QVT is a Coin of type QVT
	QVT Coin = iota + 588
	// CLO is a Coin of type CLO
	CLO Coin = iota + 599
	// ADT is a Coin of type ADT
	ADT Coin = iota + 664
	// NEO is a Coin of type NEO
	NEO Coin = iota + 665
	// LBTC is a Coin of type LBTC
	LBTC Coin = iota + 774
	// BCD is a Coin of type BCD
	BCD Coin = iota + 774
	// BTN is a Coin of type BTN
	BTN Coin = iota + 774
	// BBC is a Coin of type BBC
	BBC Coin = iota + 884
	// CDY is a Coin of type CDY
	CDY Coin = iota + 917
	// DFC is a Coin of type DFC
	DFC Coin = iota + 1108
	// BCX is a Coin of type BCX
	BCX Coin = iota + 1458
	// XTZ is a Coin of type XTZ
	XTZ Coin = iota + 1498
	// ADA is a Coin of type ADA
	ADA Coin = iota + 1583
	// XMX is a Coin of type XMX
	XMX Coin = iota + 1744
	// EGEM is a Coin of type EGEM
	EGEM Coin = iota + 1753
	// HODL is a Coin of type HODL
	HODL Coin = iota + 1754
	// QTUM is a Coin of type QTUM
	QTUM Coin = iota + 2065
	// ETP is a Coin of type ETP
	ETP Coin = iota + 2065
	// DEO is a Coin of type DEO
	DEO Coin = iota + 3314
	// NAS is a Coin of type NAS
	NAS Coin = iota + 2479
	// AXE is a Coin of type AXE
	AXE Coin = iota + 4002
	// BPA is a Coin of type BPA
	BPA Coin = iota + 6425
	// SAFE is a Coin of type SAFE
	SAFE Coin = iota + 6446
	// BTV is a Coin of type BTV
	BTV Coin = iota + 7534
	// BTQ is a Coin of type BTQ
	BTQ Coin = iota + 8095
	// BTP is a Coin of type BTP
	BTP Coin = iota + 8754
	// BTF is a Coin of type BTF
	BTF Coin = iota + 9642
	// BTCS is a Coin of type BTCS
	BTCS Coin = iota + 33631
	// ORT is a Coin of type ORT
	ORT Coin = iota + 88640
	// WICC is a Coin of type WICC
	WICC Coin = iota + 99750
	// LAX is a Coin of type LAX
	LAX Coin = iota + 1711894
	// WAN is a Coin of type WAN
	WAN Coin = iota + 5718099
	// WAVES is a Coin of type WAVES
	WAVES Coin = iota + 5741312
)

const _CoinName = "BTCTESTLTCDOGERDDDSHPPCNMCFTCXCPBLKNSRNBTMZCVIAXCHRBYGRSDGCCCNDGBMONACLAMXPMNEOSJBSZRCVTCNXTBURSTMUEZOOMVPNCDNSDCPKBPNDSTARTMOINEXPEMC2DCRXEMPARTARGSHRGCRNVCACBTCDDOPETPCAIBEDRCSYSSLRSMLYETHETCPSBLDCNXBCIOPNXSINSNOKBRITCMPCRWBELAVASHFJCMIXXVGEFLCLUBRICHXPOTQRKTRCGRCAURIXCNLGBITBBTAXMYBSDUNOMTRGBSHMCRXBIQEVOSTOBIGUPGAMEDLCZYDDBICSTRATSHMARSUBQPTCNROARKUSCTHCLINXECNDNRPINKPIGGYPIVXFLASHZENPUTZNYUNIFYXSTBRKVCXMRVOXNAVFCTECZECLSKSTEEMXZCSBTCRPTLBCKMDBSQRICXRPBCHNEBLZCLXLMNLC2WHLERCDMDBTMBIOXWCBTGBTC2XSSNTOABTXACCBCOELLAPIRLXRBVIVOFRSTHNCBUZZMBRSHSRHTMLODNONXRVNGBXBTCZPOANYCMXTWCMNXBTCPMUSICBCACRAVESTAKWBTCLCHEXCLLCCXFEEOSTRXKOBOHUSHBANANOETFOMNIBIFIUFOBISNEETBOPOBOXYBITGASKSMARTXUEZVARUCNANOARARAPBLOCKMEMPHRKOTOXRDBCSACTSSCBTWBEETQVTCLOADTNEOLBTCBCDBTNBBCCDYDFCBCXXTZADAXMXEGEMHODLQTUMETPDEONASAXEBPASAFEBTVBTQBTPBTFBTCSORTWICCLAXWANWAVES"

var _CoinMap = map[Coin]string{
	0:       _CoinName[0:3],
	1:       _CoinName[3:7],
	2:       _CoinName[7:10],
	3:       _CoinName[10:14],
	4:       _CoinName[14:17],
	5:       _CoinName[17:20],
	6:       _CoinName[20:23],
	7:       _CoinName[23:26],
	8:       _CoinName[26:29],
	9:       _CoinName[29:32],
	10:      _CoinName[32:35],
	11:      _CoinName[35:38],
	12:      _CoinName[38:41],
	13:      _CoinName[41:44],
	14:      _CoinName[44:47],
	15:      _CoinName[47:50],
	16:      _CoinName[50:53],
	17:      _CoinName[53:56],
	18:      _CoinName[56:59],
	19:      _CoinName[59:62],
	20:      _CoinName[62:65],
	22:      _CoinName[65:69],
	23:      _CoinName[69:73],
	24:      _CoinName[73:76],
	25:      _CoinName[76:80],
	26:      _CoinName[80:83],
	27:      _CoinName[83:86],
	28:      _CoinName[86:89],
	29:      _CoinName[89:92],
	30:      _CoinName[92:97],
	31:      _CoinName[97:100],
	32:      _CoinName[100:104],
	33:      _CoinName[104:107],
	34:      _CoinName[107:110],
	35:      _CoinName[110:113],
	36:      _CoinName[113:116],
	37:      _CoinName[116:119],
	38:      _CoinName[119:124],
	39:      _CoinName[124:128],
	40:      _CoinName[128:131],
	41:      _CoinName[131:135],
	42:      _CoinName[135:138],
	43:      _CoinName[138:141],
	44:      _CoinName[141:145],
	45:      _CoinName[145:148],
	48:      _CoinName[148:151],
	49:      _CoinName[151:154],
	50:      _CoinName[154:157],
	51:      _CoinName[157:159],
	52:      _CoinName[159:163],
	53:      _CoinName[163:167],
	54:      _CoinName[167:170],
	55:      _CoinName[170:173],
	56:      _CoinName[173:177],
	57:      _CoinName[177:180],
	58:      _CoinName[180:183],
	59:      _CoinName[183:187],
	60:      _CoinName[187:190],
	61:      _CoinName[190:193],
	62:      _CoinName[193:196],
	63:      _CoinName[196:200],
	65:      _CoinName[200:203],
	66:      _CoinName[203:206],
	67:      _CoinName[206:209],
	68:      _CoinName[209:213],
	69:      _CoinName[213:215],
	70:      _CoinName[215:219],
	71:      _CoinName[219:222],
	72:      _CoinName[222:225],
	73:      _CoinName[225:229],
	74:      _CoinName[229:233],
	75:      _CoinName[233:236],
	76:      _CoinName[236:239],
	77:      _CoinName[239:242],
	78:      _CoinName[242:245],
	79:      _CoinName[245:249],
	80:      _CoinName[249:254],
	81:      _CoinName[254:257],
	82:      _CoinName[257:260],
	83:      _CoinName[260:263],
	84:      _CoinName[263:266],
	85:      _CoinName[266:269],
	86:      _CoinName[269:272],
	87:      _CoinName[272:275],
	88:      _CoinName[275:279],
	89:      _CoinName[279:282],
	90:      _CoinName[282:285],
	91:      _CoinName[285:288],
	92:      _CoinName[288:291],
	93:      _CoinName[291:294],
	94:      _CoinName[294:296],
	95:      _CoinName[296:299],
	96:      _CoinName[299:302],
	97:      _CoinName[302:305],
	98:      _CoinName[305:308],
	99:      _CoinName[308:311],
	100:     _CoinName[311:316],
	101:     _CoinName[316:320],
	102:     _CoinName[320:323],
	103:     _CoinName[323:326],
	104:     _CoinName[326:330],
	105:     _CoinName[330:335],
	106:     _CoinName[335:337],
	107:     _CoinName[337:341],
	108:     _CoinName[341:344],
	109:     _CoinName[344:347],
	110:     _CoinName[347:350],
	111:     _CoinName[350:353],
	112:     _CoinName[353:356],
	113:     _CoinName[356:359],
	114:     _CoinName[359:363],
	115:     _CoinName[363:366],
	116:     _CoinName[366:369],
	117:     _CoinName[369:373],
	118:     _CoinName[373:378],
	119:     _CoinName[378:382],
	120:     _CoinName[382:387],
	121:     _CoinName[387:390],
	122:     _CoinName[390:393],
	123:     _CoinName[393:396],
	124:     _CoinName[396:401],
	125:     _CoinName[401:404],
	126:     _CoinName[404:407],
	127:     _CoinName[407:409],
	128:     _CoinName[409:412],
	129:     _CoinName[412:415],
	130:     _CoinName[415:418],
	131:     _CoinName[418:421],
	132:     _CoinName[421:423],
	133:     _CoinName[423:426],
	134:     _CoinName[426:429],
	135:     _CoinName[429:434],
	136:     _CoinName[434:437],
	137:     _CoinName[437:441],
	139:     _CoinName[441:444],
	140:     _CoinName[444:447],
	141:     _CoinName[447:450],
	142:     _CoinName[450:453],
	143:     _CoinName[453:456],
	144:     _CoinName[456:459],
	145:     _CoinName[459:462],
	146:     _CoinName[462:466],
	147:     _CoinName[466:469],
	148:     _CoinName[469:472],
	149:     _CoinName[472:476],
	150:     _CoinName[476:479],
	151:     _CoinName[479:482],
	152:     _CoinName[482:485],
	153:     _CoinName[485:488],
	154:     _CoinName[488:491],
	155:     _CoinName[491:494],
	156:     _CoinName[494:497],
	157:     _CoinName[497:502],
	158:     _CoinName[502:505],
	159:     _CoinName[505:508],
	160:     _CoinName[508:511],
	161:     _CoinName[511:514],
	162:     _CoinName[514:517],
	163:     _CoinName[517:521],
	164:     _CoinName[521:525],
	165:     _CoinName[525:528],
	166:     _CoinName[528:532],
	167:     _CoinName[532:536],
	168:     _CoinName[536:539],
	169:     _CoinName[539:543],
	170:     _CoinName[543:547],
	171:     _CoinName[547:550],
	172:     _CoinName[550:554],
	173:     _CoinName[554:557],
	174:     _CoinName[557:560],
	175:     _CoinName[560:563],
	176:     _CoinName[563:566],
	177:     _CoinName[566:570],
	178:     _CoinName[570:573],
	179:     _CoinName[573:576],
	180:     _CoinName[576:579],
	181:     _CoinName[579:581],
	182:     _CoinName[581:584],
	183:     _CoinName[584:588],
	184:     _CoinName[588:593],
	185:     _CoinName[593:596],
	186:     _CoinName[596:601],
	187:     _CoinName[601:605],
	188:     _CoinName[605:609],
	189:     _CoinName[609:612],
	190:     _CoinName[612:616],
	192:     _CoinName[616:619],
	193:     _CoinName[619:622],
	194:     _CoinName[622:625],
	195:     _CoinName[625:628],
	196:     _CoinName[628:632],
	197:     _CoinName[632:636],
	198:     _CoinName[636:642],
	199:     _CoinName[642:645],
	200:     _CoinName[645:649],
	201:     _CoinName[649:653],
	202:     _CoinName[653:656],
	209:     _CoinName[656:659],
	210:     _CoinName[659:663],
	211:     _CoinName[663:667],
	215:     _CoinName[667:671],
	222:     _CoinName[671:675],
	223:     _CoinName[675:678],
	224:     _CoinName[678:683],
	225:     _CoinName[683:687],
	233:     _CoinName[687:690],
	247:     _CoinName[690:692],
	256:     _CoinName[692:696],
	312:     _CoinName[696:699],
	321:     _CoinName[699:702],
	328:     _CoinName[702:707],
	333:     _CoinName[707:710],
	444:     _CoinName[710:713],
	510:     _CoinName[713:717],
	512:     _CoinName[717:720],
	555:     _CoinName[720:723],
	666:     _CoinName[723:726],
	668:     _CoinName[726:729],
	777:     _CoinName[729:732],
	800:     _CoinName[732:736],
	808:     _CoinName[736:739],
	820:     _CoinName[739:742],
	886:     _CoinName[742:745],
	888:     _CoinName[745:748],
	998:     _CoinName[748:752],
	999:     _CoinName[752:755],
	1000:    _CoinName[755:758],
	1111:    _CoinName[758:761],
	1145:    _CoinName[761:764],
	1337:    _CoinName[764:767],
	1688:    _CoinName[767:770],
	1729:    _CoinName[770:773],
	1815:    _CoinName[773:776],
	1977:    _CoinName[776:779],
	1987:    _CoinName[779:783],
	1989:    _CoinName[783:787],
	2301:    _CoinName[787:791],
	2302:    _CoinName[791:794],
	3552:    _CoinName[794:797],
	2718:    _CoinName[797:800],
	4242:    _CoinName[800:803],
	6666:    _CoinName[803:806],
	6688:    _CoinName[806:810],
	7777:    _CoinName[810:813],
	8339:    _CoinName[813:816],
	8999:    _CoinName[816:819],
	9888:    _CoinName[819:822],
	33878:   _CoinName[822:826],
	88888:   _CoinName[826:829],
	99999:   _CoinName[829:833],
	1712144: _CoinName[833:836],
	5718350: _CoinName[836:839],
	5741564: _CoinName[839:844],
}

func (i Coin) String() string {
	if str, ok := _CoinMap[i]; ok {
		return str
	}
	return fmt.Sprintf("Coin(%d)", i)
}

var _CoinValue = map[string]Coin{
	_CoinName[0:3]:                      0,
	strings.ToLower(_CoinName[0:3]):     0,
	_CoinName[3:7]:                      1,
	strings.ToLower(_CoinName[3:7]):     1,
	_CoinName[7:10]:                     2,
	strings.ToLower(_CoinName[7:10]):    2,
	_CoinName[10:14]:                    3,
	strings.ToLower(_CoinName[10:14]):   3,
	_CoinName[14:17]:                    4,
	strings.ToLower(_CoinName[14:17]):   4,
	_CoinName[17:20]:                    5,
	strings.ToLower(_CoinName[17:20]):   5,
	_CoinName[20:23]:                    6,
	strings.ToLower(_CoinName[20:23]):   6,
	_CoinName[23:26]:                    7,
	strings.ToLower(_CoinName[23:26]):   7,
	_CoinName[26:29]:                    8,
	strings.ToLower(_CoinName[26:29]):   8,
	_CoinName[29:32]:                    9,
	strings.ToLower(_CoinName[29:32]):   9,
	_CoinName[32:35]:                    10,
	strings.ToLower(_CoinName[32:35]):   10,
	_CoinName[35:38]:                    11,
	strings.ToLower(_CoinName[35:38]):   11,
	_CoinName[38:41]:                    12,
	strings.ToLower(_CoinName[38:41]):   12,
	_CoinName[41:44]:                    13,
	strings.ToLower(_CoinName[41:44]):   13,
	_CoinName[44:47]:                    14,
	strings.ToLower(_CoinName[44:47]):   14,
	_CoinName[47:50]:                    15,
	strings.ToLower(_CoinName[47:50]):   15,
	_CoinName[50:53]:                    16,
	strings.ToLower(_CoinName[50:53]):   16,
	_CoinName[53:56]:                    17,
	strings.ToLower(_CoinName[53:56]):   17,
	_CoinName[56:59]:                    18,
	strings.ToLower(_CoinName[56:59]):   18,
	_CoinName[59:62]:                    19,
	strings.ToLower(_CoinName[59:62]):   19,
	_CoinName[62:65]:                    20,
	strings.ToLower(_CoinName[62:65]):   20,
	_CoinName[65:69]:                    22,
	strings.ToLower(_CoinName[65:69]):   22,
	_CoinName[69:73]:                    23,
	strings.ToLower(_CoinName[69:73]):   23,
	_CoinName[73:76]:                    24,
	strings.ToLower(_CoinName[73:76]):   24,
	_CoinName[76:80]:                    25,
	strings.ToLower(_CoinName[76:80]):   25,
	_CoinName[80:83]:                    26,
	strings.ToLower(_CoinName[80:83]):   26,
	_CoinName[83:86]:                    27,
	strings.ToLower(_CoinName[83:86]):   27,
	_CoinName[86:89]:                    28,
	strings.ToLower(_CoinName[86:89]):   28,
	_CoinName[89:92]:                    29,
	strings.ToLower(_CoinName[89:92]):   29,
	_CoinName[92:97]:                    30,
	strings.ToLower(_CoinName[92:97]):   30,
	_CoinName[97:100]:                   31,
	strings.ToLower(_CoinName[97:100]):  31,
	_CoinName[100:104]:                  32,
	strings.ToLower(_CoinName[100:104]): 32,
	_CoinName[104:107]:                  33,
	strings.ToLower(_CoinName[104:107]): 33,
	_CoinName[107:110]:                  34,
	strings.ToLower(_CoinName[107:110]): 34,
	_CoinName[110:113]:                  35,
	strings.ToLower(_CoinName[110:113]): 35,
	_CoinName[113:116]:                  36,
	strings.ToLower(_CoinName[113:116]): 36,
	_CoinName[116:119]:                  37,
	strings.ToLower(_CoinName[116:119]): 37,
	_CoinName[119:124]:                  38,
	strings.ToLower(_CoinName[119:124]): 38,
	_CoinName[124:128]:                  39,
	strings.ToLower(_CoinName[124:128]): 39,
	_CoinName[128:131]:                  40,
	strings.ToLower(_CoinName[128:131]): 40,
	_CoinName[131:135]:                  41,
	strings.ToLower(_CoinName[131:135]): 41,
	_CoinName[135:138]:                  42,
	strings.ToLower(_CoinName[135:138]): 42,
	_CoinName[138:141]:                  43,
	strings.ToLower(_CoinName[138:141]): 43,
	_CoinName[141:145]:                  44,
	strings.ToLower(_CoinName[141:145]): 44,
	_CoinName[145:148]:                  45,
	strings.ToLower(_CoinName[145:148]): 45,
	_CoinName[148:151]:                  48,
	strings.ToLower(_CoinName[148:151]): 48,
	_CoinName[151:154]:                  49,
	strings.ToLower(_CoinName[151:154]): 49,
	_CoinName[154:157]:                  50,
	strings.ToLower(_CoinName[154:157]): 50,
	_CoinName[157:159]:                  51,
	strings.ToLower(_CoinName[157:159]): 51,
	_CoinName[159:163]:                  52,
	strings.ToLower(_CoinName[159:163]): 52,
	_CoinName[163:167]:                  53,
	strings.ToLower(_CoinName[163:167]): 53,
	_CoinName[167:170]:                  54,
	strings.ToLower(_CoinName[167:170]): 54,
	_CoinName[170:173]:                  55,
	strings.ToLower(_CoinName[170:173]): 55,
	_CoinName[173:177]:                  56,
	strings.ToLower(_CoinName[173:177]): 56,
	_CoinName[177:180]:                  57,
	strings.ToLower(_CoinName[177:180]): 57,
	_CoinName[180:183]:                  58,
	strings.ToLower(_CoinName[180:183]): 58,
	_CoinName[183:187]:                  59,
	strings.ToLower(_CoinName[183:187]): 59,
	_CoinName[187:190]:                  60,
	strings.ToLower(_CoinName[187:190]): 60,
	_CoinName[190:193]:                  61,
	strings.ToLower(_CoinName[190:193]): 61,
	_CoinName[193:196]:                  62,
	strings.ToLower(_CoinName[193:196]): 62,
	_CoinName[196:200]:                  63,
	strings.ToLower(_CoinName[196:200]): 63,
	_CoinName[200:203]:                  65,
	strings.ToLower(_CoinName[200:203]): 65,
	_CoinName[203:206]:                  66,
	strings.ToLower(_CoinName[203:206]): 66,
	_CoinName[206:209]:                  67,
	strings.ToLower(_CoinName[206:209]): 67,
	_CoinName[209:213]:                  68,
	strings.ToLower(_CoinName[209:213]): 68,
	_CoinName[213:215]:                  69,
	strings.ToLower(_CoinName[213:215]): 69,
	_CoinName[215:219]:                  70,
	strings.ToLower(_CoinName[215:219]): 70,
	_CoinName[219:222]:                  71,
	strings.ToLower(_CoinName[219:222]): 71,
	_CoinName[222:225]:                  72,
	strings.ToLower(_CoinName[222:225]): 72,
	_CoinName[225:229]:                  73,
	strings.ToLower(_CoinName[225:229]): 73,
	_CoinName[229:233]:                  74,
	strings.ToLower(_CoinName[229:233]): 74,
	_CoinName[233:236]:                  75,
	strings.ToLower(_CoinName[233:236]): 75,
	_CoinName[236:239]:                  76,
	strings.ToLower(_CoinName[236:239]): 76,
	_CoinName[239:242]:                  77,
	strings.ToLower(_CoinName[239:242]): 77,
	_CoinName[242:245]:                  78,
	strings.ToLower(_CoinName[242:245]): 78,
	_CoinName[245:249]:                  79,
	strings.ToLower(_CoinName[245:249]): 79,
	_CoinName[249:254]:                  80,
	strings.ToLower(_CoinName[249:254]): 80,
	_CoinName[254:257]:                  81,
	strings.ToLower(_CoinName[254:257]): 81,
	_CoinName[257:260]:                  82,
	strings.ToLower(_CoinName[257:260]): 82,
	_CoinName[260:263]:                  83,
	strings.ToLower(_CoinName[260:263]): 83,
	_CoinName[263:266]:                  84,
	strings.ToLower(_CoinName[263:266]): 84,
	_CoinName[266:269]:                  85,
	strings.ToLower(_CoinName[266:269]): 85,
	_CoinName[269:272]:                  86,
	strings.ToLower(_CoinName[269:272]): 86,
	_CoinName[272:275]:                  87,
	strings.ToLower(_CoinName[272:275]): 87,
	_CoinName[275:279]:                  88,
	strings.ToLower(_CoinName[275:279]): 88,
	_CoinName[279:282]:                  89,
	strings.ToLower(_CoinName[279:282]): 89,
	_CoinName[282:285]:                  90,
	strings.ToLower(_CoinName[282:285]): 90,
	_CoinName[285:288]:                  91,
	strings.ToLower(_CoinName[285:288]): 91,
	_CoinName[288:291]:                  92,
	strings.ToLower(_CoinName[288:291]): 92,
	_CoinName[291:294]:                  93,
	strings.ToLower(_CoinName[291:294]): 93,
	_CoinName[294:296]:                  94,
	strings.ToLower(_CoinName[294:296]): 94,
	_CoinName[296:299]:                  95,
	strings.ToLower(_CoinName[296:299]): 95,
	_CoinName[299:302]:                  96,
	strings.ToLower(_CoinName[299:302]): 96,
	_CoinName[302:305]:                  97,
	strings.ToLower(_CoinName[302:305]): 97,
	_CoinName[305:308]:                  98,
	strings.ToLower(_CoinName[305:308]): 98,
	_CoinName[308:311]:                  99,
	strings.ToLower(_CoinName[308:311]): 99,
	_CoinName[311:316]:                  100,
	strings.ToLower(_CoinName[311:316]): 100,
	_CoinName[316:320]:                  101,
	strings.ToLower(_CoinName[316:320]): 101,
	_CoinName[320:323]:                  102,
	strings.ToLower(_CoinName[320:323]): 102,
	_CoinName[323:326]:                  103,
	strings.ToLower(_CoinName[323:326]): 103,
	_CoinName[326:330]:                  104,
	strings.ToLower(_CoinName[326:330]): 104,
	_CoinName[330:335]:                  105,
	strings.ToLower(_CoinName[330:335]): 105,
	_CoinName[335:337]:                  106,
	strings.ToLower(_CoinName[335:337]): 106,
	_CoinName[337:341]:                  107,
	strings.ToLower(_CoinName[337:341]): 107,
	_CoinName[341:344]:                  108,
	strings.ToLower(_CoinName[341:344]): 108,
	_CoinName[344:347]:                  109,
	strings.ToLower(_CoinName[344:347]): 109,
	_CoinName[347:350]:                  110,
	strings.ToLower(_CoinName[347:350]): 110,
	_CoinName[350:353]:                  111,
	strings.ToLower(_CoinName[350:353]): 111,
	_CoinName[353:356]:                  112,
	strings.ToLower(_CoinName[353:356]): 112,
	_CoinName[356:359]:                  113,
	strings.ToLower(_CoinName[356:359]): 113,
	_CoinName[359:363]:                  114,
	strings.ToLower(_CoinName[359:363]): 114,
	_CoinName[363:366]:                  115,
	strings.ToLower(_CoinName[363:366]): 115,
	_CoinName[366:369]:                  116,
	strings.ToLower(_CoinName[366:369]): 116,
	_CoinName[369:373]:                  117,
	strings.ToLower(_CoinName[369:373]): 117,
	_CoinName[373:378]:                  118,
	strings.ToLower(_CoinName[373:378]): 118,
	_CoinName[378:382]:                  119,
	strings.ToLower(_CoinName[378:382]): 119,
	_CoinName[382:387]:                  120,
	strings.ToLower(_CoinName[382:387]): 120,
	_CoinName[387:390]:                  121,
	strings.ToLower(_CoinName[387:390]): 121,
	_CoinName[390:393]:                  122,
	strings.ToLower(_CoinName[390:393]): 122,
	_CoinName[393:396]:                  123,
	strings.ToLower(_CoinName[393:396]): 123,
	_CoinName[396:401]:                  124,
	strings.ToLower(_CoinName[396:401]): 124,
	_CoinName[401:404]:                  125,
	strings.ToLower(_CoinName[401:404]): 125,
	_CoinName[404:407]:                  126,
	strings.ToLower(_CoinName[404:407]): 126,
	_CoinName[407:409]:                  127,
	strings.ToLower(_CoinName[407:409]): 127,
	_CoinName[409:412]:                  128,
	strings.ToLower(_CoinName[409:412]): 128,
	_CoinName[412:415]:                  129,
	strings.ToLower(_CoinName[412:415]): 129,
	_CoinName[415:418]:                  130,
	strings.ToLower(_CoinName[415:418]): 130,
	_CoinName[418:421]:                  131,
	strings.ToLower(_CoinName[418:421]): 131,
	_CoinName[421:423]:                  132,
	strings.ToLower(_CoinName[421:423]): 132,
	_CoinName[423:426]:                  133,
	strings.ToLower(_CoinName[423:426]): 133,
	_CoinName[426:429]:                  134,
	strings.ToLower(_CoinName[426:429]): 134,
	_CoinName[429:434]:                  135,
	strings.ToLower(_CoinName[429:434]): 135,
	_CoinName[434:437]:                  136,
	strings.ToLower(_CoinName[434:437]): 136,
	_CoinName[437:441]:                  137,
	strings.ToLower(_CoinName[437:441]): 137,
	_CoinName[441:444]:                  139,
	strings.ToLower(_CoinName[441:444]): 139,
	_CoinName[444:447]:                  140,
	strings.ToLower(_CoinName[444:447]): 140,
	_CoinName[447:450]:                  141,
	strings.ToLower(_CoinName[447:450]): 141,
	_CoinName[450:453]:                  142,
	strings.ToLower(_CoinName[450:453]): 142,
	_CoinName[453:456]:                  143,
	strings.ToLower(_CoinName[453:456]): 143,
	_CoinName[456:459]:                  144,
	strings.ToLower(_CoinName[456:459]): 144,
	_CoinName[459:462]:                  145,
	strings.ToLower(_CoinName[459:462]): 145,
	_CoinName[462:466]:                  146,
	strings.ToLower(_CoinName[462:466]): 146,
	_CoinName[466:469]:                  147,
	strings.ToLower(_CoinName[466:469]): 147,
	_CoinName[469:472]:                  148,
	strings.ToLower(_CoinName[469:472]): 148,
	_CoinName[472:476]:                  149,
	strings.ToLower(_CoinName[472:476]): 149,
	_CoinName[476:479]:                  150,
	strings.ToLower(_CoinName[476:479]): 150,
	_CoinName[479:482]:                  151,
	strings.ToLower(_CoinName[479:482]): 151,
	_CoinName[482:485]:                  152,
	strings.ToLower(_CoinName[482:485]): 152,
	_CoinName[485:488]:                  153,
	strings.ToLower(_CoinName[485:488]): 153,
	_CoinName[488:491]:                  154,
	strings.ToLower(_CoinName[488:491]): 154,
	_CoinName[491:494]:                  155,
	strings.ToLower(_CoinName[491:494]): 155,
	_CoinName[494:497]:                  156,
	strings.ToLower(_CoinName[494:497]): 156,
	_CoinName[497:502]:                  157,
	strings.ToLower(_CoinName[497:502]): 157,
	_CoinName[502:505]:                  158,
	strings.ToLower(_CoinName[502:505]): 158,
	_CoinName[505:508]:                  159,
	strings.ToLower(_CoinName[505:508]): 159,
	_CoinName[508:511]:                  160,
	strings.ToLower(_CoinName[508:511]): 160,
	_CoinName[511:514]:                  161,
	strings.ToLower(_CoinName[511:514]): 161,
	_CoinName[514:517]:                  162,
	strings.ToLower(_CoinName[514:517]): 162,
	_CoinName[517:521]:                  163,
	strings.ToLower(_CoinName[517:521]): 163,
	_CoinName[521:525]:                  164,
	strings.ToLower(_CoinName[521:525]): 164,
	_CoinName[525:528]:                  165,
	strings.ToLower(_CoinName[525:528]): 165,
	_CoinName[528:532]:                  166,
	strings.ToLower(_CoinName[528:532]): 166,
	_CoinName[532:536]:                  167,
	strings.ToLower(_CoinName[532:536]): 167,
	_CoinName[536:539]:                  168,
	strings.ToLower(_CoinName[536:539]): 168,
	_CoinName[539:543]:                  169,
	strings.ToLower(_CoinName[539:543]): 169,
	_CoinName[543:547]:                  170,
	strings.ToLower(_CoinName[543:547]): 170,
	_CoinName[547:550]:                  171,
	strings.ToLower(_CoinName[547:550]): 171,
	_CoinName[550:554]:                  172,
	strings.ToLower(_CoinName[550:554]): 172,
	_CoinName[554:557]:                  173,
	strings.ToLower(_CoinName[554:557]): 173,
	_CoinName[557:560]:                  174,
	strings.ToLower(_CoinName[557:560]): 174,
	_CoinName[560:563]:                  175,
	strings.ToLower(_CoinName[560:563]): 175,
	_CoinName[563:566]:                  176,
	strings.ToLower(_CoinName[563:566]): 176,
	_CoinName[566:570]:                  177,
	strings.ToLower(_CoinName[566:570]): 177,
	_CoinName[570:573]:                  178,
	strings.ToLower(_CoinName[570:573]): 178,
	_CoinName[573:576]:                  179,
	strings.ToLower(_CoinName[573:576]): 179,
	_CoinName[576:579]:                  180,
	strings.ToLower(_CoinName[576:579]): 180,
	_CoinName[579:581]:                  181,
	strings.ToLower(_CoinName[579:581]): 181,
	_CoinName[581:584]:                  182,
	strings.ToLower(_CoinName[581:584]): 182,
	_CoinName[584:588]:                  183,
	strings.ToLower(_CoinName[584:588]): 183,
	_CoinName[588:593]:                  184,
	strings.ToLower(_CoinName[588:593]): 184,
	_CoinName[593:596]:                  185,
	strings.ToLower(_CoinName[593:596]): 185,
	_CoinName[596:601]:                  186,
	strings.ToLower(_CoinName[596:601]): 186,
	_CoinName[601:605]:                  187,
	strings.ToLower(_CoinName[601:605]): 187,
	_CoinName[605:609]:                  188,
	strings.ToLower(_CoinName[605:609]): 188,
	_CoinName[609:612]:                  189,
	strings.ToLower(_CoinName[609:612]): 189,
	_CoinName[612:616]:                  190,
	strings.ToLower(_CoinName[612:616]): 190,
	_CoinName[616:619]:                  192,
	strings.ToLower(_CoinName[616:619]): 192,
	_CoinName[619:622]:                  193,
	strings.ToLower(_CoinName[619:622]): 193,
	_CoinName[622:625]:                  194,
	strings.ToLower(_CoinName[622:625]): 194,
	_CoinName[625:628]:                  195,
	strings.ToLower(_CoinName[625:628]): 195,
	_CoinName[628:632]:                  196,
	strings.ToLower(_CoinName[628:632]): 196,
	_CoinName[632:636]:                  197,
	strings.ToLower(_CoinName[632:636]): 197,
	_CoinName[636:642]:                  198,
	strings.ToLower(_CoinName[636:642]): 198,
	_CoinName[642:645]:                  199,
	strings.ToLower(_CoinName[642:645]): 199,
	_CoinName[645:649]:                  200,
	strings.ToLower(_CoinName[645:649]): 200,
	_CoinName[649:653]:                  201,
	strings.ToLower(_CoinName[649:653]): 201,
	_CoinName[653:656]:                  202,
	strings.ToLower(_CoinName[653:656]): 202,
	_CoinName[656:659]:                  209,
	strings.ToLower(_CoinName[656:659]): 209,
	_CoinName[659:663]:                  210,
	strings.ToLower(_CoinName[659:663]): 210,
	_CoinName[663:667]:                  211,
	strings.ToLower(_CoinName[663:667]): 211,
	_CoinName[667:671]:                  215,
	strings.ToLower(_CoinName[667:671]): 215,
	_CoinName[671:675]:                  222,
	strings.ToLower(_CoinName[671:675]): 222,
	_CoinName[675:678]:                  223,
	strings.ToLower(_CoinName[675:678]): 223,
	_CoinName[678:683]:                  224,
	strings.ToLower(_CoinName[678:683]): 224,
	_CoinName[683:687]:                  225,
	strings.ToLower(_CoinName[683:687]): 225,
	_CoinName[687:690]:                  233,
	strings.ToLower(_CoinName[687:690]): 233,
	_CoinName[690:692]:                  247,
	strings.ToLower(_CoinName[690:692]): 247,
	_CoinName[692:696]:                  256,
	strings.ToLower(_CoinName[692:696]): 256,
	_CoinName[696:699]:                  312,
	strings.ToLower(_CoinName[696:699]): 312,
	_CoinName[699:702]:                  321,
	strings.ToLower(_CoinName[699:702]): 321,
	_CoinName[702:707]:                  328,
	strings.ToLower(_CoinName[702:707]): 328,
	_CoinName[707:710]:                  333,
	strings.ToLower(_CoinName[707:710]): 333,
	_CoinName[710:713]:                  444,
	strings.ToLower(_CoinName[710:713]): 444,
	_CoinName[713:717]:                  510,
	strings.ToLower(_CoinName[713:717]): 510,
	_CoinName[717:720]:                  512,
	strings.ToLower(_CoinName[717:720]): 512,
	_CoinName[720:723]:                  555,
	strings.ToLower(_CoinName[720:723]): 555,
	_CoinName[723:726]:                  666,
	strings.ToLower(_CoinName[723:726]): 666,
	_CoinName[726:729]:                  668,
	strings.ToLower(_CoinName[726:729]): 668,
	_CoinName[729:732]:                  777,
	strings.ToLower(_CoinName[729:732]): 777,
	_CoinName[732:736]:                  800,
	strings.ToLower(_CoinName[732:736]): 800,
	_CoinName[736:739]:                  808,
	strings.ToLower(_CoinName[736:739]): 808,
	_CoinName[739:742]:                  820,
	strings.ToLower(_CoinName[739:742]): 820,
	_CoinName[742:745]:                  886,
	strings.ToLower(_CoinName[742:745]): 886,
	_CoinName[745:748]:                  888,
	strings.ToLower(_CoinName[745:748]): 888,
	_CoinName[748:752]:                  998,
	strings.ToLower(_CoinName[748:752]): 998,
	_CoinName[752:755]:                  999,
	strings.ToLower(_CoinName[752:755]): 999,
	_CoinName[755:758]:                  1000,
	strings.ToLower(_CoinName[755:758]): 1000,
	_CoinName[758:761]:                  1111,
	strings.ToLower(_CoinName[758:761]): 1111,
	_CoinName[761:764]:                  1145,
	strings.ToLower(_CoinName[761:764]): 1145,
	_CoinName[764:767]:                  1337,
	strings.ToLower(_CoinName[764:767]): 1337,
	_CoinName[767:770]:                  1688,
	strings.ToLower(_CoinName[767:770]): 1688,
	_CoinName[770:773]:                  1729,
	strings.ToLower(_CoinName[770:773]): 1729,
	_CoinName[773:776]:                  1815,
	strings.ToLower(_CoinName[773:776]): 1815,
	_CoinName[776:779]:                  1977,
	strings.ToLower(_CoinName[776:779]): 1977,
	_CoinName[779:783]:                  1987,
	strings.ToLower(_CoinName[779:783]): 1987,
	_CoinName[783:787]:                  1989,
	strings.ToLower(_CoinName[783:787]): 1989,
	_CoinName[787:791]:                  2301,
	strings.ToLower(_CoinName[787:791]): 2301,
	_CoinName[791:794]:                  2302,
	strings.ToLower(_CoinName[791:794]): 2302,
	_CoinName[794:797]:                  3552,
	strings.ToLower(_CoinName[794:797]): 3552,
	_CoinName[797:800]:                  2718,
	strings.ToLower(_CoinName[797:800]): 2718,
	_CoinName[800:803]:                  4242,
	strings.ToLower(_CoinName[800:803]): 4242,
	_CoinName[803:806]:                  6666,
	strings.ToLower(_CoinName[803:806]): 6666,
	_CoinName[806:810]:                  6688,
	strings.ToLower(_CoinName[806:810]): 6688,
	_CoinName[810:813]:                  7777,
	strings.ToLower(_CoinName[810:813]): 7777,
	_CoinName[813:816]:                  8339,
	strings.ToLower(_CoinName[813:816]): 8339,
	_CoinName[816:819]:                  8999,
	strings.ToLower(_CoinName[816:819]): 8999,
	_CoinName[819:822]:                  9888,
	strings.ToLower(_CoinName[819:822]): 9888,
	_CoinName[822:826]:                  33878,
	strings.ToLower(_CoinName[822:826]): 33878,
	_CoinName[826:829]:                  88888,
	strings.ToLower(_CoinName[826:829]): 88888,
	_CoinName[829:833]:                  99999,
	strings.ToLower(_CoinName[829:833]): 99999,
	_CoinName[833:836]:                  1712144,
	strings.ToLower(_CoinName[833:836]): 1712144,
	_CoinName[836:839]:                  5718350,
	strings.ToLower(_CoinName[836:839]): 5718350,
	_CoinName[839:844]:                  5741564,
	strings.ToLower(_CoinName[839:844]): 5741564,
}

// ParseCoin attempts to convert a string to a Coin
func ParseCoin(name string) (Coin, error) {
	if x, ok := _CoinValue[name]; ok {
		return Coin(x), nil
	}
	return Coin(0), fmt.Errorf("%s is not a valid Coin", name)
}

func (x *Coin) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

func (x *Coin) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseCoin(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}
